/// Purpose: Exercise the external-executable media backend against a real
/// FFmpeg, on a machine that has one.
/// Inputs: An FFmpeg the locator can find, or one the download helper fetches.
/// Returns: None.
/// Side effects: Runs FFmpeg, and in the download test performs network I/O and
/// writes about a hundred megabytes into a temporary directory.
/// Notes: **These tests are opt-in.** The toolkit group is skipped when no
/// FFmpeg is installed, and the download group runs only with
/// `--dart-define=live_download=true`, because a large download does not belong
/// in a suite that is run on every change.
///
/// Run the toolkit tests:
///   flutter test test/media_toolkit_live_test.dart
/// Run the download test as well:
///   flutter test test/media_toolkit_live_test.dart --dart-define=live_download=true
///
/// The fixture is generated by FFmpeg itself rather than committed, so the repo
/// carries no binary test data and the audio is exactly the length the tests
/// assert against.
library;

import 'dart:ffi' show Abi;
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:my_transcribe/features/local/services/pcm_window_cutter.dart';
import 'package:my_transcribe/features/media/services/external_ffmpeg_media_toolkit.dart';
import 'package:my_transcribe/features/media/services/ffmpeg_downloader.dart';
import 'package:my_transcribe/features/media/services/ffmpeg_locator.dart';
import 'package:my_transcribe/features/media/services/media_toolkit.dart';
import 'package:path/path.dart' as p;

import 'golden/pcm_header.dart';

/// Whether the large download test should run.
const _liveDownload = bool.fromEnvironment('live_download');

void main() {
  group('the external FFmpeg backend', () {
    late Directory work;
    late ExternalFfmpegMediaToolkit toolkit;
    late String fixture;
    var available = false;

    /// Purpose: Skip the current test when this machine has no FFmpeg.
    /// Inputs: None; reads [available].
    /// Returns: `true` when the caller should return immediately.
    /// Side effects: Marks the running test as skipped.
    /// Notes: Internal helper used within this file only. A `skip:` argument
    /// cannot be used here: it is evaluated when the test is *registered*,
    /// which is before `setUpAll` has looked for FFmpeg, so it would always
    /// read the initial `false` and skip even on a machine that has one.
    bool skipWithoutFfmpeg() {
      if (available) return false;
      markTestSkipped('no FFmpeg on this machine');
      return true;
    }

    setUpAll(() async {
      work = await Directory.systemTemp.createTemp('mytranscribe_media_');
      toolkit = ExternalFfmpegMediaToolkit(locator: FfmpegLocator());
      available = (await toolkit.status()).available;
      if (!available) return;

      // A 30-second tone, generated by the tool under test. Two channels and
      // 44.1 kHz so normalizing has something real to change.
      fixture = p.join(work.path, 'fixture.mp3');
      final ffmpeg = await FfmpegLocator().locate('ffmpeg');
      final result = await Process.run(ffmpeg!.path, [
        '-hide_banner',
        '-loglevel',
        'error',
        '-y',
        '-f',
        'lavfi',
        '-i',
        'sine=frequency=440:sample_rate=44100:duration=30',
        '-ac',
        '2',
        '-c:a',
        'libmp3lame',
        '-b:a',
        '128k',
        fixture,
      ]);
      if (result.exitCode != 0) {
        fail('could not build the fixture: ${result.stderr}');
      }
    });

    tearDownAll(() async {
      try {
        await work.delete(recursive: true);
      } catch (_) {
        // Windows can hold a handle briefly.
      }
    });

    test('reports itself available and names a version', () async {
      if (skipWithoutFfmpeg()) return;
      final status = await toolkit.status();
      expect(status.available, isTrue);
      expect(status.detail, contains('ffmpeg'));
      expect(status.ffmpegPath, isNotNull);
      expect(status.ffprobePath, isNotNull);
    });

    test('probes duration and stream details', () async {
      if (skipWithoutFfmpeg()) return;
      final info = await toolkit.probe(fixture);
      expect(info.durationSeconds, closeTo(30, 0.5));
      expect(info.audioCodec, 'mp3');
      expect(info.sampleRate, 44100);
      expect(info.channels, 2);
      expect(info.hasVideo, isFalse);
      expect(info.hasAudio, isTrue);
      expect(info.formattedDuration, '0:30');
    });

    test('refuses a file that is not media', () async {
      if (skipWithoutFfmpeg()) return;
      final notAudio = File(p.join(work.path, 'notes.txt'))
        ..writeAsStringSync('this is not a recording');
      await expectLater(
        toolkit.probe(notAudio.path),
        throwsA(
          isA<MediaException>().having(
            (e) => e.kind,
            'kind',
            MediaFailureKind.badInput,
          ),
        ),
      );
    });

    test('refuses a file that is not there', () async {
      if (skipWithoutFfmpeg()) return;
      await expectLater(
        toolkit.probe(p.join(work.path, 'missing.mp3')),
        throwsA(
          isA<MediaException>().having(
            (e) => e.kind,
            'kind',
            MediaFailureKind.badInput,
          ),
        ),
      );
    });

    test('normalizes to mono 16 kHz and reports progress', () async {
      if (skipWithoutFfmpeg()) return;
      final output = p.join(work.path, 'audio.mp3');
      final fractions = <double?>[];
      await toolkit.normalize(
        fixture,
        output,
        onProgress: (fraction, _) => fractions.add(fraction),
      );

      final info = await toolkit.probe(output);
      expect(info.channels, 1);
      expect(info.sampleRate, 16000);
      expect(info.durationSeconds, closeTo(30, 0.5));

      // The whole point of fixing the encode settings: a second of audio is
      // 8000 bytes, which is what makes a window's size predictable.
      final bytes = await File(output).length();
      expect(bytes, closeTo(30 * 8000, 30 * 8000 * 0.15));

      expect(fractions, isNotEmpty);
      expect(fractions.whereType<double>().last, closeTo(1.0, 0.05));
    });

    test('extracts a window without re-encoding it', () async {
      if (skipWithoutFfmpeg()) return;
      final normalized = p.join(work.path, 'audio.mp3');
      if (!File(normalized).existsSync()) {
        await toolkit.normalize(fixture, normalized);
      }
      final window = p.join(work.path, 'chunk_0000.mp3');
      await toolkit.extractWindow(normalized, 10, 8, window);

      final info = await toolkit.probe(window);
      // A stream copy cuts on a frame boundary, so the length is close rather
      // than exact — which is why nothing downstream assumes otherwise.
      expect(info.durationSeconds, closeTo(8, 0.2));
      expect(info.channels, 1);
      expect(info.sampleRate, 16000);
    });

    test('cuts a PCM window a local engine can take', () async {
      if (skipWithoutFfmpeg()) return;
      final normalized = p.join(work.path, 'audio.mp3');
      if (!File(normalized).existsSync()) {
        await toolkit.normalize(fixture, normalized);
      }
    final window = File(p.join(work.path, 'chunk_0000.wav'));
    final pcm = await PcmWindowCutter(toolkit).cut(normalized, 5, 8, window);

    // Decoded rather than copied, so the length is exact to the sample, and
    // bit-exact, so the header is the same whichever FFmpeg cut it.
    expect(pcm.sampleCount, 8 * pcmSampleRate);
    expect(pcm.dataOffset, 44);
    expect(
      window.readAsBytesSync().sublist(0, 44),
      expectedPcmHeader(8 * pcmSampleRate),
    );
    });

    test('cuts a WAV sample at the requested point', () async {
      if (skipWithoutFfmpeg()) return;
      final normalized = p.join(work.path, 'audio.mp3');
      if (!File(normalized).existsSync()) {
        await toolkit.normalize(fixture, normalized);
      }
      final sample = p.join(work.path, 'speaker.wav');
      await toolkit.cutSample(normalized, 5, 3, sample);

      final info = await toolkit.probe(sample);
      expect(info.durationSeconds, closeTo(3, 0.1));
      expect(info.audioCodec, 'pcm_s16le');
      expect(info.sampleRate, 16000);
      expect(info.channels, 1);
    });

    test('cancelling stops the work and leaves no partial file', () async {
      if (skipWithoutFfmpeg()) return;
      final output = p.join(work.path, 'cancelled.mp3');
      final cancel = MediaCancelToken();
      final running = toolkit.normalize(fixture, output, cancel: cancel);
      cancel.cancel();

      await expectLater(
        running,
        throwsA(
          isA<MediaException>().having(
            (e) => e.kind,
            'kind',
            MediaFailureKind.cancelled,
          ),
        ),
      );
      // A half-written window left behind would be reused by a resume, whose
      // only check is the file's size.
      expect(File(output).existsSync(), isFalse);
      await cancel.dispose();
    });

    test('a missing tool is reported as missing, not as a crash', () async {
      final empty = await Directory.systemTemp.createTemp('mytranscribe_none_');
      addTearDown(() => empty.delete(recursive: true));
      final none = ExternalFfmpegMediaToolkit(
        locator: FfmpegLocator(searchPath: const []),
      );

      final status = await none.status();
      expect(status.available, isFalse);
      expect(status.detail, contains('not found'));
    });
  });

  group('the download helper', () {
    test('names the right asset for each Windows architecture', () {
      // No network: this is the rule, not the download.
      final arm = FfmpegDownloader(
        destination: Directory.systemTemp,
        abi: Abi.windowsArm64,
      ).plan();
      expect(arm.assetName, 'ffmpeg-master-latest-winarm64-lgpl.zip');
      expect(arm.url, startsWith('https://github.com/BtbN/FFmpeg-Builds/'));

      final x64 = FfmpegDownloader(
        destination: Directory.systemTemp,
        abi: Abi.windowsX64,
      ).plan();
      expect(x64.assetName, 'ffmpeg-master-latest-win64-lgpl.zip');
    });

    test('refuses an architecture with no published build', () {
      expect(
        () => FfmpegDownloader(
          destination: Directory.systemTemp,
          abi: Abi.linuxRiscv64,
        ).plan(),
        throwsA(
          isA<MediaException>().having(
            (e) => e.kind,
            'kind',
            MediaFailureKind.toolMissing,
          ),
        ),
      );
    });

    test(
      'downloads, extracts and verifies a real build',
      () async {
        final into = await Directory.systemTemp.createTemp('mytranscribe_dl_');
        addTearDown(() async {
          try {
            await into.delete(recursive: true);
          } catch (_) {}
        });

        final stages = <FfmpegDownloadStage>[];
        final path = await FfmpegDownloader(destination: into).download(
          onProgress: (progress) {
            if (stages.isEmpty || stages.last != progress.stage) {
              stages.add(progress.stage);
            }
          },
        );

        expect(File(path).existsSync(), isTrue);
        expect(
          File(p.join(into.path, 'ffprobe.exe')).existsSync(),
          isTrue,
          reason: 'ffprobe is extracted alongside ffmpeg',
        );
        expect(File(p.join(into.path, 'manifest.json')).existsSync(), isTrue);
        expect(
          File(p.join(into.path, 'download.zip')).existsSync(),
          isFalse,
          reason: 'the archive is removed once it has been unpacked',
        );
        expect(stages, contains(FfmpegDownloadStage.downloading));
        expect(stages.last, FfmpegDownloadStage.done);

        // And the locator finds what the downloader left behind.
        final tool = await FfmpegLocator(
          downloadDirectory: into,
          searchPath: const [],
        ).locate('ffmpeg');
        expect(tool!.source, FfmpegSource.downloaded);
      },
      timeout: const Timeout(Duration(minutes: 10)),
      skip: !_liveDownload
          ? 'pass --dart-define=live_download=true to run this'
          : (!Platform.isWindows ? 'Windows only' : null),
    );
  });
}
