/// Purpose: Regenerate the Dart bindings from the vendored sherpa-onnx header.
/// Inputs: Optionally the path to `libclang` as the first argument; otherwise
/// Visual Studio's LLVM component on Windows, then ffigen's default places.
/// Returns: None.
/// Side effects: Rewrites `lib/src/sherpa_bindings.g.dart`.
/// Notes: Run after `third_party/sherpa-onnx/c-api.h` changes, which happens
/// only when `native/binaries.json` moves to a new sherpa-onnx version — the
/// bindings must describe exactly the version the libraries are (decisions
/// D21 and D22 of the local-models plan). Run from this package:
/// `dart run tool/ffigen.dart`.
library;

import 'dart:ffi' show Abi;
import 'dart:io';

import 'package:ffigen/ffigen.dart';

/// The C-API entry points the app uses: one offline recognizer, its streams
/// and their results. Everything they reference comes along, so the config
/// structs are generated from the header.
const _functions = {
  'SherpaOnnxGetVersionStr',
  'SherpaOnnxCreateOfflineRecognizer',
  'SherpaOnnxDestroyOfflineRecognizer',
  'SherpaOnnxCreateOfflineStream',
  'SherpaOnnxDestroyOfflineStream',
  'SherpaOnnxAcceptWaveformOffline',
  'SherpaOnnxDecodeOfflineStream',
  'SherpaOnnxGetOfflineStreamResult',
  'SherpaOnnxDestroyOfflineRecognizerResult',
};

/// Purpose: Generate the binding file.
/// Inputs: [args], optionally the libclang path.
/// Returns: None.
/// Side effects: Writes the generated file.
/// Notes: None.
Future<void> main(List<String> args) async {
  final root = Platform.script.resolve('../');
  final include = root.resolve('third_party/sherpa-onnx/');
  final libclang = args.isNotEmpty ? args.first : _visualStudioLibclang();
  await FfiGenerator(
    input: Input(
      entryPoints: [include.resolve('c-api.h')],
      compilerOptions: ['-I${include.toFilePath()}'],
    ),
    output: Output(
      dart: DartOutput(path: root.resolve('lib/src/sherpa_bindings.g.dart')),
      preamble:
          '// Generated by tool/ffigen.dart from the vendored sherpa-onnx\n'
          '// header (third_party/sherpa-onnx). Do not edit by hand.\n'
          '// ignore_for_file: type=lint',
      style: const NativeExternalBindings(
        assetId: 'package:local_asr_sherpa/sherpa',
      ),
    ),
    visitors: [
      Visitor(
        func: (f) => f.isIncluded = _functions.contains(f.name),
        // Structs reached only through a pointer would otherwise be opaque;
        // the recognizer's config and result must be laid out in full.
        struct: (s) {
          if (s.name.startsWith('SherpaOnnxOffline') ||
              s.name == 'SherpaOnnxFeatureConfig' ||
              s.name == 'SherpaOnnxHomophoneReplacerConfig') {
            s.isIncluded = true;
          }
        },
      ),
    ],
  ).generate(libclangDylib: libclang == null ? null : Uri.file(libclang));
}

/// Purpose: Find libclang in Visual Studio's LLVM component.
/// Inputs: None.
/// Returns: Its path, or null to let ffigen search its default places.
/// Side effects: Runs `vswhere` on Windows.
/// Notes: The component matches the host: ARM64 on an ARM64 machine.
String? _visualStudioLibclang() {
  if (!Platform.isWindows) return null;
  final vswhere =
      '${Platform.environment['ProgramFiles(x86)']}\\Microsoft Visual Studio\\Installer\\vswhere.exe';
  if (!File(vswhere).existsSync()) return null;
  final result = Process.runSync(vswhere, [
    '-latest',
    '-property',
    'installationPath',
  ]);
  final vs = '${result.stdout}'.trim();
  final arch = Abi.current() == Abi.windowsArm64 ? 'ARM64' : 'x64';
  final dll = '$vs\\VC\\Tools\\Llvm\\$arch\\bin\\libclang.dll';
  return File(dll).existsSync() ? dll : null;
}
