// Generated by tool/ffigen.dart from the vendored whisper.cpp
// headers (third_party/whisper.cpp). Do not edit by hand.
// ignore_for_file: type=lint
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// The ggml functions the app calls, looked up in whichever loaded library exports them.
class GgmlBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  GgmlBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  GgmlBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int ggml_backend_dev_count() {
    return _ggml_backend_dev_count();
  }

  late final _ggml_backend_dev_countPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function()>>(
        'ggml_backend_dev_count',
      );
  late final _ggml_backend_dev_count = _ggml_backend_dev_countPtr
      .asFunction<int Function()>();

  ffi.Pointer<ffi.Char> ggml_backend_dev_description(
    ffi.Pointer<ggml_backend_device> device,
  ) {
    return _ggml_backend_dev_description(device);
  }

  late final _ggml_backend_dev_descriptionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ggml_backend_device>)
        >
      >('ggml_backend_dev_description');
  late final _ggml_backend_dev_description = _ggml_backend_dev_descriptionPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<ggml_backend_device>)
      >();

  ffi.Pointer<ggml_backend_device> ggml_backend_dev_get(int index) {
    return _ggml_backend_dev_get(index);
  }

  late final _ggml_backend_dev_getPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<ggml_backend_device> Function(ffi.Size)>
      >('ggml_backend_dev_get');
  late final _ggml_backend_dev_get = _ggml_backend_dev_getPtr
      .asFunction<ffi.Pointer<ggml_backend_device> Function(int)>();

  ffi.Pointer<ffi.Char> ggml_backend_dev_name(
    ffi.Pointer<ggml_backend_device> device,
  ) {
    return _ggml_backend_dev_name(device);
  }

  late final _ggml_backend_dev_namePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ggml_backend_device>)
        >
      >('ggml_backend_dev_name');
  late final _ggml_backend_dev_name = _ggml_backend_dev_namePtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<ggml_backend_device>)
      >();

  ggml_backend_dev_type ggml_backend_dev_type$1(
    ffi.Pointer<ggml_backend_device> device,
  ) {
    return ggml_backend_dev_type.fromValue(_ggml_backend_dev_type(device));
  }

  late final _ggml_backend_dev_type$1Ptr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<ggml_backend_device>)
        >
      >('ggml_backend_dev_type');
  late final _ggml_backend_dev_type = _ggml_backend_dev_type$1Ptr
      .asFunction<int Function(ffi.Pointer<ggml_backend_device>)>();

  void ggml_backend_load_all_from_path(ffi.Pointer<ffi.Char> dir_path) {
    return _ggml_backend_load_all_from_path(dir_path);
  }

  late final _ggml_backend_load_all_from_pathPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'ggml_backend_load_all_from_path',
      );
  late final _ggml_backend_load_all_from_path =
      _ggml_backend_load_all_from_pathPtr
          .asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  int ggml_backend_reg_count() {
    return _ggml_backend_reg_count();
  }

  late final _ggml_backend_reg_countPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function()>>(
        'ggml_backend_reg_count',
      );
  late final _ggml_backend_reg_count = _ggml_backend_reg_countPtr
      .asFunction<int Function()>();

  void ggml_log_set(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.UnsignedInt level,
          ffi.Pointer<ffi.Char> text,
          ffi.Pointer<ffi.Void> user_data,
        )
      >
    >
    log_callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _ggml_log_set(log_callback, user_data);
  }

  late final _ggml_log_setPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<
              ffi.NativeFunction<
                ffi.Void Function(
                  ffi.UnsignedInt level,
                  ffi.Pointer<ffi.Char> text,
                  ffi.Pointer<ffi.Void> user_data,
                )
              >
            >,
            ffi.Pointer<ffi.Void>,
          )
        >
      >('ggml_log_set');
  late final _ggml_log_set = _ggml_log_setPtr
      .asFunction<
        void Function(
          ffi.Pointer<
            ffi.NativeFunction<
              ffi.Void Function(
                ffi.UnsignedInt level,
                ffi.Pointer<ffi.Char> text,
                ffi.Pointer<ffi.Void> user_data,
              )
            >
          >,
          ffi.Pointer<ffi.Void>,
        )
      >();
}

enum ggml_backend_dev_type {
  GGML_BACKEND_DEVICE_TYPE_CPU(0),
  GGML_BACKEND_DEVICE_TYPE_GPU(1),
  GGML_BACKEND_DEVICE_TYPE_IGPU(2),
  GGML_BACKEND_DEVICE_TYPE_ACCEL(3),
  GGML_BACKEND_DEVICE_TYPE_META(4);

  final int value;
  const ggml_backend_dev_type(this.value);

  static ggml_backend_dev_type fromValue(int value) => switch (value) {
    0 => GGML_BACKEND_DEVICE_TYPE_CPU,
    1 => GGML_BACKEND_DEVICE_TYPE_GPU,
    2 => GGML_BACKEND_DEVICE_TYPE_IGPU,
    3 => GGML_BACKEND_DEVICE_TYPE_ACCEL,
    4 => GGML_BACKEND_DEVICE_TYPE_META,
    _ => throw ArgumentError('Unknown value for ggml_backend_dev_type: $value'),
  };
}

final class ggml_backend_device extends ffi.Opaque {}

enum ggml_log_level {
  GGML_LOG_LEVEL_NONE(0),
  GGML_LOG_LEVEL_DEBUG(1),
  GGML_LOG_LEVEL_INFO(2),
  GGML_LOG_LEVEL_WARN(3),
  GGML_LOG_LEVEL_ERROR(4),
  GGML_LOG_LEVEL_CONT(5);

  final int value;
  const ggml_log_level(this.value);

  static ggml_log_level fromValue(int value) => switch (value) {
    0 => GGML_LOG_LEVEL_NONE,
    1 => GGML_LOG_LEVEL_DEBUG,
    2 => GGML_LOG_LEVEL_INFO,
    3 => GGML_LOG_LEVEL_WARN,
    4 => GGML_LOG_LEVEL_ERROR,
    5 => GGML_LOG_LEVEL_CONT,
    _ => throw ArgumentError('Unknown value for ggml_log_level: $value'),
  };
}
