// Generated by tool/ffigen.dart from the vendored whisper.cpp
// headers (third_party/whisper.cpp). Do not edit by hand.
// ignore_for_file: type=lint
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// whisper.cpp's Parakeet functions, looked up in whichever loaded library exports them.
class ParakeetBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  ParakeetBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  ParakeetBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  parakeet_context_params parakeet_context_default_params() {
    return _parakeet_context_default_params();
  }

  late final _parakeet_context_default_paramsPtr =
      _lookup<ffi.NativeFunction<parakeet_context_params Function()>>(
        'parakeet_context_default_params',
      );
  late final _parakeet_context_default_params =
      _parakeet_context_default_paramsPtr
          .asFunction<parakeet_context_params Function()>();

  void parakeet_free(ffi.Pointer<parakeet_context> ctx) {
    return _parakeet_free(ctx);
  }

  late final _parakeet_freePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<parakeet_context>)>
      >('parakeet_free');
  late final _parakeet_free = _parakeet_freePtr
      .asFunction<void Function(ffi.Pointer<parakeet_context>)>();

  int parakeet_full(
    ffi.Pointer<parakeet_context> ctx,
    parakeet_full_params params,
    ffi.Pointer<ffi.Float> samples,
    int n_samples,
  ) {
    return _parakeet_full(ctx, params, samples, n_samples);
  }

  late final _parakeet_fullPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<parakeet_context>,
            parakeet_full_params,
            ffi.Pointer<ffi.Float>,
            ffi.Int,
          )
        >
      >('parakeet_full');
  late final _parakeet_full = _parakeet_fullPtr
      .asFunction<
        int Function(
          ffi.Pointer<parakeet_context>,
          parakeet_full_params,
          ffi.Pointer<ffi.Float>,
          int,
        )
      >();

  parakeet_full_params parakeet_full_default_params(
    parakeet_sampling_strategy strategy,
  ) {
    return _parakeet_full_default_params(strategy.value);
  }

  late final _parakeet_full_default_paramsPtr =
      _lookup<
        ffi.NativeFunction<parakeet_full_params Function(ffi.UnsignedInt)>
      >('parakeet_full_default_params');
  late final _parakeet_full_default_params = _parakeet_full_default_paramsPtr
      .asFunction<parakeet_full_params Function(int)>();

  parakeet_token_data parakeet_full_get_token_data(
    ffi.Pointer<parakeet_context> ctx,
    int i_segment,
    int i_token,
  ) {
    return _parakeet_full_get_token_data(ctx, i_segment, i_token);
  }

  late final _parakeet_full_get_token_dataPtr =
      _lookup<
        ffi.NativeFunction<
          parakeet_token_data Function(
            ffi.Pointer<parakeet_context>,
            ffi.Int,
            ffi.Int,
          )
        >
      >('parakeet_full_get_token_data');
  late final _parakeet_full_get_token_data = _parakeet_full_get_token_dataPtr
      .asFunction<
        parakeet_token_data Function(ffi.Pointer<parakeet_context>, int, int)
      >();

  ffi.Pointer<ffi.Char> parakeet_full_get_token_text(
    ffi.Pointer<parakeet_context> ctx,
    int i_segment,
    int i_token,
  ) {
    return _parakeet_full_get_token_text(ctx, i_segment, i_token);
  }

  late final _parakeet_full_get_token_textPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<parakeet_context>,
            ffi.Int,
            ffi.Int,
          )
        >
      >('parakeet_full_get_token_text');
  late final _parakeet_full_get_token_text = _parakeet_full_get_token_textPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<parakeet_context>, int, int)
      >();

  int parakeet_full_n_segments(ffi.Pointer<parakeet_context> ctx) {
    return _parakeet_full_n_segments(ctx);
  }

  late final _parakeet_full_n_segmentsPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<parakeet_context>)>
      >('parakeet_full_n_segments');
  late final _parakeet_full_n_segments = _parakeet_full_n_segmentsPtr
      .asFunction<int Function(ffi.Pointer<parakeet_context>)>();

  int parakeet_full_n_tokens(ffi.Pointer<parakeet_context> ctx, int i_segment) {
    return _parakeet_full_n_tokens(ctx, i_segment);
  }

  late final _parakeet_full_n_tokensPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<parakeet_context>, ffi.Int)
        >
      >('parakeet_full_n_tokens');
  late final _parakeet_full_n_tokens = _parakeet_full_n_tokensPtr
      .asFunction<int Function(ffi.Pointer<parakeet_context>, int)>();

  ffi.Pointer<parakeet_context> parakeet_init_from_file_with_params(
    ffi.Pointer<ffi.Char> path_model,
    parakeet_context_params params,
  ) {
    return _parakeet_init_from_file_with_params(path_model, params);
  }

  late final _parakeet_init_from_file_with_paramsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<parakeet_context> Function(
            ffi.Pointer<ffi.Char>,
            parakeet_context_params,
          )
        >
      >('parakeet_init_from_file_with_params');
  late final _parakeet_init_from_file_with_params =
      _parakeet_init_from_file_with_paramsPtr
          .asFunction<
            ffi.Pointer<parakeet_context> Function(
              ffi.Pointer<ffi.Char>,
              parakeet_context_params,
            )
          >();

  ffi.Pointer<ffi.Char> parakeet_print_system_info() {
    return _parakeet_print_system_info();
  }

  late final _parakeet_print_system_infoPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'parakeet_print_system_info',
      );
  late final _parakeet_print_system_info = _parakeet_print_system_infoPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> parakeet_version() {
    return _parakeet_version();
  }

  late final _parakeet_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'parakeet_version',
      );
  late final _parakeet_version = _parakeet_versionPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();
}

final class parakeet_context extends ffi.Opaque {}

final class parakeet_context_params extends ffi.Struct {
  @ffi.Bool()
  external bool use_gpu;

  @ffi.Int()
  external int gpu_device;

  static ffi.Pointer<parakeet_context_params> $allocate(
    ffi.Allocator $allocator, {
    required bool use_gpu,
    required int gpu_device,
  }) => $allocator<parakeet_context_params>()
    ..ref.use_gpu = use_gpu
    ..ref.gpu_device = gpu_device;
}

final class parakeet_full_params extends ffi.Struct {
  @ffi.UnsignedInt()
  external int strategyAsInt;

  parakeet_sampling_strategy get strategy =>
      parakeet_sampling_strategy.fromValue(strategyAsInt);
  set strategy(parakeet_sampling_strategy value) => strategyAsInt = value.value;

  @ffi.Int()
  external int n_threads;

  @ffi.Int()
  external int offset_ms;

  @ffi.Int()
  external int duration_ms;

  @ffi.Bool()
  external bool no_context;

  @ffi.Int()
  external int audio_ctx;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<parakeet_context> ctx,
        ffi.Pointer<parakeet_state> state,
        ffi.Int n_new,
        ffi.Pointer<ffi.Void> user_data,
      )
    >
  >
  new_segment_callback;

  external ffi.Pointer<ffi.Void> new_segment_callback_user_data;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<parakeet_context> ctx,
        ffi.Pointer<parakeet_state> state,
        ffi.Pointer<parakeet_token_data> token_data,
        ffi.Pointer<ffi.Void> user_data,
      )
    >
  >
  new_token_callback;

  external ffi.Pointer<ffi.Void> new_token_callback_user_data;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<parakeet_context> ctx,
        ffi.Pointer<parakeet_state> state,
        ffi.Int progress,
        ffi.Pointer<ffi.Void> user_data,
      )
    >
  >
  progress_callback;

  external ffi.Pointer<ffi.Void> progress_callback_user_data;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Bool Function(
        ffi.Pointer<parakeet_context> ctx,
        ffi.Pointer<parakeet_state> state,
        ffi.Pointer<ffi.Void> user_data,
      )
    >
  >
  encoder_begin_callback;

  external ffi.Pointer<ffi.Void> encoder_begin_callback_user_data;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Void> data)>
  >
  abort_callback;

  external ffi.Pointer<ffi.Void> abort_callback_user_data;

  static ffi.Pointer<parakeet_full_params> $allocate(
    ffi.Allocator $allocator, {
    required parakeet_sampling_strategy strategy,
    required int n_threads,
    required int offset_ms,
    required int duration_ms,
    required bool no_context,
    required int audio_ctx,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<parakeet_context> ctx,
          ffi.Pointer<parakeet_state> state,
          ffi.Int n_new,
          ffi.Pointer<ffi.Void> user_data,
        )
      >
    >
    new_segment_callback,
    required ffi.Pointer<ffi.Void> new_segment_callback_user_data,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<parakeet_context> ctx,
          ffi.Pointer<parakeet_state> state,
          ffi.Pointer<parakeet_token_data> token_data,
          ffi.Pointer<ffi.Void> user_data,
        )
      >
    >
    new_token_callback,
    required ffi.Pointer<ffi.Void> new_token_callback_user_data,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<parakeet_context> ctx,
          ffi.Pointer<parakeet_state> state,
          ffi.Int progress,
          ffi.Pointer<ffi.Void> user_data,
        )
      >
    >
    progress_callback,
    required ffi.Pointer<ffi.Void> progress_callback_user_data,
    required ffi.Pointer<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<parakeet_context> ctx,
          ffi.Pointer<parakeet_state> state,
          ffi.Pointer<ffi.Void> user_data,
        )
      >
    >
    encoder_begin_callback,
    required ffi.Pointer<ffi.Void> encoder_begin_callback_user_data,
    required ffi.Pointer<
      ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Void> data)>
    >
    abort_callback,
    required ffi.Pointer<ffi.Void> abort_callback_user_data,
  }) => $allocator<parakeet_full_params>()
    ..ref.strategy = strategy
    ..ref.n_threads = n_threads
    ..ref.offset_ms = offset_ms
    ..ref.duration_ms = duration_ms
    ..ref.no_context = no_context
    ..ref.audio_ctx = audio_ctx
    ..ref.new_segment_callback = new_segment_callback
    ..ref.new_segment_callback_user_data = new_segment_callback_user_data
    ..ref.new_token_callback = new_token_callback
    ..ref.new_token_callback_user_data = new_token_callback_user_data
    ..ref.progress_callback = progress_callback
    ..ref.progress_callback_user_data = progress_callback_user_data
    ..ref.encoder_begin_callback = encoder_begin_callback
    ..ref.encoder_begin_callback_user_data = encoder_begin_callback_user_data
    ..ref.abort_callback = abort_callback
    ..ref.abort_callback_user_data = abort_callback_user_data;
}

enum parakeet_sampling_strategy {
  PARAKEET_SAMPLING_GREEDY(0);

  final int value;
  const parakeet_sampling_strategy(this.value);

  static parakeet_sampling_strategy fromValue(int value) => switch (value) {
    0 => PARAKEET_SAMPLING_GREEDY,
    _ => throw ArgumentError(
      'Unknown value for parakeet_sampling_strategy: $value',
    ),
  };
}

final class parakeet_state extends ffi.Opaque {}

final class parakeet_token_data extends ffi.Struct {
  @ffi.Int32()
  external int id;

  @ffi.Int()
  external int duration_idx;

  @ffi.Int()
  external int duration_value;

  @ffi.Int()
  external int frame_index;

  @ffi.Float()
  external double p;

  @ffi.Float()
  external double plog;

  @ffi.Int64()
  external int t0;

  @ffi.Int64()
  external int t1;

  @ffi.Bool()
  external bool is_word_start;

  static ffi.Pointer<parakeet_token_data> $allocate(
    ffi.Allocator $allocator, {
    required int id,
    required int duration_idx,
    required int duration_value,
    required int frame_index,
    required double p,
    required double plog,
    required int t0,
    required int t1,
    required bool is_word_start,
  }) => $allocator<parakeet_token_data>()
    ..ref.id = id
    ..ref.duration_idx = duration_idx
    ..ref.duration_value = duration_value
    ..ref.frame_index = frame_index
    ..ref.p = p
    ..ref.plog = plog
    ..ref.t0 = t0
    ..ref.t1 = t1
    ..ref.is_word_start = is_word_start;
}
