// Generated by tool/ffigen.dart from the vendored whisper.cpp
// headers (third_party/whisper.cpp). Do not edit by hand.
// ignore_for_file: type=lint
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
@ffi.DefaultAsset('package:local_asr_whisper/whisper')
library;

import 'dart:ffi' as ffi;

@ffi.Native<whisper_context_params Function()>()
external whisper_context_params whisper_context_default_params();

@ffi.Native<ffi.Void Function(ffi.Pointer<whisper_context>)>()
external void whisper_free(ffi.Pointer<whisper_context> ctx);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<whisper_context>,
    whisper_full_params,
    ffi.Pointer<ffi.Float>,
    ffi.Int,
  )
>()
external int whisper_full(
  ffi.Pointer<whisper_context> ctx,
  whisper_full_params params,
  ffi.Pointer<ffi.Float> samples,
  int n_samples,
);

@ffi.Native<whisper_full_params Function(ffi.UnsignedInt)>(
  symbol: 'whisper_full_default_params',
)
external whisper_full_params _whisper_full_default_params(int strategy);

whisper_full_params whisper_full_default_params(
  whisper_sampling_strategy strategy,
) {
  return _whisper_full_default_params(strategy.value);
}

@ffi.Native<ffi.Int64 Function(ffi.Pointer<whisper_context>, ffi.Int)>()
external int whisper_full_get_segment_t0(
  ffi.Pointer<whisper_context> ctx,
  int i_segment,
);

@ffi.Native<ffi.Int64 Function(ffi.Pointer<whisper_context>, ffi.Int)>()
external int whisper_full_get_segment_t1(
  ffi.Pointer<whisper_context> ctx,
  int i_segment,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<whisper_context>, ffi.Int)
>()
external ffi.Pointer<ffi.Char> whisper_full_get_segment_text(
  ffi.Pointer<whisper_context> ctx,
  int i_segment,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<whisper_context>)>()
external int whisper_full_lang_id(ffi.Pointer<whisper_context> ctx);

@ffi.Native<ffi.Int Function(ffi.Pointer<whisper_context>)>()
external int whisper_full_n_segments(ffi.Pointer<whisper_context> ctx);

@ffi.Native<
  ffi.Pointer<whisper_context> Function(
    ffi.Pointer<ffi.Char>,
    whisper_context_params,
  )
>()
external ffi.Pointer<whisper_context> whisper_init_from_file_with_params(
  ffi.Pointer<ffi.Char> path_model,
  whisper_context_params params,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int)>()
external ffi.Pointer<ffi.Char> whisper_lang_str(int id);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.UnsignedInt level,
          ffi.Pointer<ffi.Char> text,
          ffi.Pointer<ffi.Void> user_data,
        )
      >
    >,
    ffi.Pointer<ffi.Void>,
  )
>()
external void whisper_log_set(
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.UnsignedInt level,
        ffi.Pointer<ffi.Char> text,
        ffi.Pointer<ffi.Void> user_data,
      )
    >
  >
  log_callback,
  ffi.Pointer<ffi.Void> user_data,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> whisper_print_system_info();

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> whisper_version();

final class UnnamedStruct extends ffi.Struct {
  @ffi.Int()
  external int best_of;

  static ffi.Pointer<UnnamedStruct> $allocate(
    ffi.Allocator $allocator, {
    required int best_of,
  }) => $allocator<UnnamedStruct>()..ref.best_of = best_of;
}

final class UnnamedStruct$1 extends ffi.Struct {
  @ffi.Int()
  external int beam_size;

  @ffi.Float()
  external double patience;

  static ffi.Pointer<UnnamedStruct$1> $allocate(
    ffi.Allocator $allocator, {
    required int beam_size,
    required double patience,
  }) => $allocator<UnnamedStruct$1>()
    ..ref.beam_size = beam_size
    ..ref.patience = patience;
}

enum ggml_log_level {
  GGML_LOG_LEVEL_NONE(0),
  GGML_LOG_LEVEL_DEBUG(1),
  GGML_LOG_LEVEL_INFO(2),
  GGML_LOG_LEVEL_WARN(3),
  GGML_LOG_LEVEL_ERROR(4),
  GGML_LOG_LEVEL_CONT(5);

  final int value;
  const ggml_log_level(this.value);

  static ggml_log_level fromValue(int value) => switch (value) {
    0 => GGML_LOG_LEVEL_NONE,
    1 => GGML_LOG_LEVEL_DEBUG,
    2 => GGML_LOG_LEVEL_INFO,
    3 => GGML_LOG_LEVEL_WARN,
    4 => GGML_LOG_LEVEL_ERROR,
    5 => GGML_LOG_LEVEL_CONT,
    _ => throw ArgumentError('Unknown value for ggml_log_level: $value'),
  };
}

final class whisper_ahead extends ffi.Opaque {}

final class whisper_aheads extends ffi.Struct {
  @ffi.Size()
  external int n_heads;

  external ffi.Pointer<whisper_ahead> heads;

  static ffi.Pointer<whisper_aheads> $allocate(
    ffi.Allocator $allocator, {
    required int n_heads,
    required ffi.Pointer<whisper_ahead> heads,
  }) => $allocator<whisper_aheads>()
    ..ref.n_heads = n_heads
    ..ref.heads = heads;
}

enum whisper_alignment_heads_preset {
  WHISPER_AHEADS_NONE(0),
  WHISPER_AHEADS_N_TOP_MOST(1),
  WHISPER_AHEADS_CUSTOM(2),
  WHISPER_AHEADS_TINY_EN(3),
  WHISPER_AHEADS_TINY(4),
  WHISPER_AHEADS_BASE_EN(5),
  WHISPER_AHEADS_BASE(6),
  WHISPER_AHEADS_SMALL_EN(7),
  WHISPER_AHEADS_SMALL(8),
  WHISPER_AHEADS_MEDIUM_EN(9),
  WHISPER_AHEADS_MEDIUM(10),
  WHISPER_AHEADS_LARGE_V1(11),
  WHISPER_AHEADS_LARGE_V2(12),
  WHISPER_AHEADS_LARGE_V3(13),
  WHISPER_AHEADS_LARGE_V3_TURBO(14);

  final int value;
  const whisper_alignment_heads_preset(this.value);

  static whisper_alignment_heads_preset fromValue(int value) => switch (value) {
    0 => WHISPER_AHEADS_NONE,
    1 => WHISPER_AHEADS_N_TOP_MOST,
    2 => WHISPER_AHEADS_CUSTOM,
    3 => WHISPER_AHEADS_TINY_EN,
    4 => WHISPER_AHEADS_TINY,
    5 => WHISPER_AHEADS_BASE_EN,
    6 => WHISPER_AHEADS_BASE,
    7 => WHISPER_AHEADS_SMALL_EN,
    8 => WHISPER_AHEADS_SMALL,
    9 => WHISPER_AHEADS_MEDIUM_EN,
    10 => WHISPER_AHEADS_MEDIUM,
    11 => WHISPER_AHEADS_LARGE_V1,
    12 => WHISPER_AHEADS_LARGE_V2,
    13 => WHISPER_AHEADS_LARGE_V3,
    14 => WHISPER_AHEADS_LARGE_V3_TURBO,
    _ => throw ArgumentError(
      'Unknown value for whisper_alignment_heads_preset: $value',
    ),
  };
}

final class whisper_context extends ffi.Opaque {}

final class whisper_context_params extends ffi.Struct {
  @ffi.Bool()
  external bool use_gpu;

  @ffi.Bool()
  external bool flash_attn;

  @ffi.Int()
  external int gpu_device;

  @ffi.Bool()
  external bool dtw_token_timestamps;

  @ffi.UnsignedInt()
  external int dtw_aheads_presetAsInt;

  whisper_alignment_heads_preset get dtw_aheads_preset =>
      whisper_alignment_heads_preset.fromValue(dtw_aheads_presetAsInt);
  set dtw_aheads_preset(whisper_alignment_heads_preset value) =>
      dtw_aheads_presetAsInt = value.value;

  @ffi.Int()
  external int dtw_n_top;

  external whisper_aheads dtw_aheads;

  @ffi.Size()
  external int dtw_mem_size;
}

final class whisper_full_params extends ffi.Struct {
  @ffi.UnsignedInt()
  external int strategyAsInt;

  whisper_sampling_strategy get strategy =>
      whisper_sampling_strategy.fromValue(strategyAsInt);
  set strategy(whisper_sampling_strategy value) => strategyAsInt = value.value;

  @ffi.Int()
  external int n_threads;

  @ffi.Int()
  external int n_max_text_ctx;

  @ffi.Int()
  external int offset_ms;

  @ffi.Int()
  external int duration_ms;

  @ffi.Bool()
  external bool translate;

  @ffi.Bool()
  external bool no_context;

  @ffi.Bool()
  external bool no_timestamps;

  @ffi.Bool()
  external bool single_segment;

  @ffi.Bool()
  external bool print_special;

  @ffi.Bool()
  external bool print_progress;

  @ffi.Bool()
  external bool print_realtime;

  @ffi.Bool()
  external bool print_timestamps;

  @ffi.Bool()
  external bool token_timestamps;

  @ffi.Float()
  external double thold_pt;

  @ffi.Float()
  external double thold_ptsum;

  @ffi.Int()
  external int max_len;

  @ffi.Bool()
  external bool split_on_word;

  @ffi.Int()
  external int max_tokens;

  @ffi.Bool()
  external bool debug_mode;

  @ffi.Int()
  external int audio_ctx;

  @ffi.Bool()
  external bool tdrz_enable;

  external ffi.Pointer<ffi.Char> suppress_regex;

  external ffi.Pointer<ffi.Char> initial_prompt;

  @ffi.Bool()
  external bool carry_initial_prompt;

  external ffi.Pointer<ffi.Int32> prompt_tokens;

  @ffi.Int()
  external int prompt_n_tokens;

  external ffi.Pointer<ffi.Char> language;

  @ffi.Bool()
  external bool detect_language;

  @ffi.Bool()
  external bool suppress_blank;

  @ffi.Bool()
  external bool suppress_nst;

  @ffi.Float()
  external double temperature;

  @ffi.Float()
  external double max_initial_ts;

  @ffi.Float()
  external double length_penalty;

  @ffi.Float()
  external double temperature_inc;

  @ffi.Float()
  external double entropy_thold;

  @ffi.Float()
  external double logprob_thold;

  @ffi.Float()
  external double no_speech_thold;

  external UnnamedStruct greedy;

  external UnnamedStruct$1 beam_search;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<whisper_context> ctx,
        ffi.Pointer<whisper_state> state,
        ffi.Int n_new,
        ffi.Pointer<ffi.Void> user_data,
      )
    >
  >
  new_segment_callback;

  external ffi.Pointer<ffi.Void> new_segment_callback_user_data;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<whisper_context> ctx,
        ffi.Pointer<whisper_state> state,
        ffi.Int progress,
        ffi.Pointer<ffi.Void> user_data,
      )
    >
  >
  progress_callback;

  external ffi.Pointer<ffi.Void> progress_callback_user_data;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Bool Function(
        ffi.Pointer<whisper_context> ctx,
        ffi.Pointer<whisper_state> state,
        ffi.Pointer<ffi.Void> user_data,
      )
    >
  >
  encoder_begin_callback;

  external ffi.Pointer<ffi.Void> encoder_begin_callback_user_data;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Void> data)>
  >
  abort_callback;

  external ffi.Pointer<ffi.Void> abort_callback_user_data;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<whisper_context> ctx,
        ffi.Pointer<whisper_state> state,
        ffi.Pointer<whisper_token_data> tokens,
        ffi.Int n_tokens,
        ffi.Pointer<ffi.Float> logits,
        ffi.Pointer<ffi.Void> user_data,
      )
    >
  >
  logits_filter_callback;

  external ffi.Pointer<ffi.Void> logits_filter_callback_user_data;

  external ffi.Pointer<ffi.Pointer<whisper_grammar_element>> grammar_rules;

  @ffi.Size()
  external int n_grammar_rules;

  @ffi.Size()
  external int i_start_rule;

  @ffi.Float()
  external double grammar_penalty;

  @ffi.Bool()
  external bool vad;

  external ffi.Pointer<ffi.Char> vad_model_path;

  external whisper_vad_params vad_params;
}

final class whisper_grammar_element extends ffi.Opaque {}

/// /////////////////////////////////////////////////////////////////////////
enum whisper_sampling_strategy {
  WHISPER_SAMPLING_GREEDY(0),
  WHISPER_SAMPLING_BEAM_SEARCH(1);

  final int value;
  const whisper_sampling_strategy(this.value);

  static whisper_sampling_strategy fromValue(int value) => switch (value) {
    0 => WHISPER_SAMPLING_GREEDY,
    1 => WHISPER_SAMPLING_BEAM_SEARCH,
    _ => throw ArgumentError(
      'Unknown value for whisper_sampling_strategy: $value',
    ),
  };
}

final class whisper_state extends ffi.Opaque {}

final class whisper_token_data extends ffi.Opaque {}

final class whisper_vad_params extends ffi.Struct {
  @ffi.Float()
  external double threshold;

  @ffi.Int()
  external int min_speech_duration_ms;

  @ffi.Int()
  external int min_silence_duration_ms;

  @ffi.Float()
  external double max_speech_duration_s;

  @ffi.Int()
  external int speech_pad_ms;

  @ffi.Float()
  external double samples_overlap;

  static ffi.Pointer<whisper_vad_params> $allocate(
    ffi.Allocator $allocator, {
    required double threshold,
    required int min_speech_duration_ms,
    required int min_silence_duration_ms,
    required double max_speech_duration_s,
    required int speech_pad_ms,
    required double samples_overlap,
  }) => $allocator<whisper_vad_params>()
    ..ref.threshold = threshold
    ..ref.min_speech_duration_ms = min_speech_duration_ms
    ..ref.min_silence_duration_ms = min_silence_duration_ms
    ..ref.max_speech_duration_s = max_speech_duration_s
    ..ref.speech_pad_ms = speech_pad_ms
    ..ref.samples_overlap = samples_overlap;
}
