/// Purpose: Prove the linked-in FFmpeg libraries actually load and run on a
/// real device.
/// Inputs: None; the fixture is generated on the device by FFmpeg itself.
/// Returns: None.
/// Side effects: Runs FFmpeg in the app process and writes into the app's
/// temporary directory.
/// Notes: This is the one thing no test on the host machine can answer. The
/// native archives are downloaded at build time and linked in, so "the APK
/// built" is not evidence that the libraries work — a wrong architecture or a
/// stripped symbol fails at the first real call, on the device, in front of the
/// user. Run it with a device attached:
///
///   `flutter test integration_test/media_toolkit_test.dart -d <device id>`
///
/// The assertions mirror `test/media_toolkit_live_test.dart`, which covers the
/// external-executable backend on desktop, so the two backends are held to the
/// same behaviour.
library;

import 'dart:io';

import 'package:ffmpeg_kit_flutter_new_audio/ffmpeg_kit.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:my_transcribe/features/media/services/embedded_ffmpeg_media_toolkit.dart';
import 'package:my_transcribe/features/media/services/media_toolkit.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  const toolkit = EmbeddedFfmpegMediaToolkit();
  late Directory work;
  late String fixture;

  setUpAll(() async {
    work = await Directory(
      p.join((await getTemporaryDirectory()).path, 'media_toolkit_test'),
    ).create(recursive: true);

    // A 20-second tone, generated by the libraries under test. Stereo at
    // 44.1 kHz, so normalizing has something real to change.
    fixture = p.join(work.path, 'fixture.mp3');
    await generateFixture(fixture);
  });

  tearDownAll(() async {
    try {
      await work.delete(recursive: true);
    } catch (_) {}
  });

  testWidgets('the libraries load and report themselves available', (_) async {
    final status = await toolkit.status();
    expect(status.available, isTrue, reason: status.detail);
    expect(status.detail, 'Built in');
  });

  testWidgets('probes duration and stream details', (_) async {
    final info = await toolkit.probe(fixture);
    expect(info.durationSeconds, closeTo(20, 0.5));
    expect(info.audioCodec, 'mp3');
    expect(info.sampleRate, 44100);
    expect(info.channels, 2);
    expect(info.hasVideo, isFalse);
  });

  testWidgets('refuses a file that is not media', (_) async {
    final notAudio = File(p.join(work.path, 'notes.txt'))
      ..writeAsStringSync('this is not a recording');
    await expectLater(
      toolkit.probe(notAudio.path),
      throwsA(
        isA<MediaException>().having(
          (e) => e.kind,
          'kind',
          MediaFailureKind.badInput,
        ),
      ),
    );
  });

  testWidgets('normalizes to mono 16 kHz at the predicted size', (_) async {
    final output = p.join(work.path, 'audio.mp3');
    final fractions = <double?>[];
    await toolkit.normalize(
      fixture,
      output,
      onProgress: (fraction, _) => fractions.add(fraction),
    );

    final info = await toolkit.probe(output);
    expect(info.channels, 1);
    expect(info.sampleRate, 16000);

    // The byte budget the chunk planner relies on: 8000 bytes a second. It has
    // to hold on the device as well as on the desktop, or a window planned on
    // one and cut on the other would come out the wrong size.
    final bytes = await File(output).length();
    expect(bytes, closeTo(20 * 8000, 20 * 8000 * 0.15));

    expect(fractions, isNotEmpty);
  });

  testWidgets('extracts a window and cuts a sample', (_) async {
    final normalized = p.join(work.path, 'audio.mp3');
    if (!File(normalized).existsSync()) {
      await toolkit.normalize(fixture, normalized);
    }

    final window = p.join(work.path, 'chunk_0000.mp3');
    await toolkit.extractWindow(normalized, 5, 8, window);
    final windowInfo = await toolkit.probe(window);
    expect(windowInfo.durationSeconds, closeTo(8, 0.3));
    expect(windowInfo.sampleRate, 16000);

    final sample = p.join(work.path, 'speaker.wav');
    await toolkit.cutSample(normalized, 2, 3, sample);
    final sampleInfo = await toolkit.probe(sample);
    expect(sampleInfo.durationSeconds, closeTo(3, 0.2));
    expect(sampleInfo.audioCodec, 'pcm_s16le');
    expect(sampleInfo.channels, 1);
  });

  testWidgets('a cancelled operation reports itself cancelled', (_) async {
    final output = p.join(work.path, 'cancelled.mp3');
    final cancel = MediaCancelToken();
    final running = toolkit.normalize(fixture, output, cancel: cancel);
    cancel.cancel();

    await expectLater(
      running,
      throwsA(
        isA<MediaException>().having(
          (e) => e.kind,
          'kind',
          MediaFailureKind.cancelled,
        ),
      ),
    );
    await cancel.dispose();
  });
}

/// Purpose: Write a 20-second stereo tone using the libraries under test.
/// Inputs: [destination].
/// Returns: A future completing when the file exists.
/// Side effects: Runs FFmpeg in this process; writes the file.
/// Notes: Generated rather than committed, so the repository carries no binary
/// test data and the audio is exactly the length the tests assert against.
/// `lavfi` synthesises audio with no input file, which is the only way to get a
/// fixture onto a device without shipping one.
///
/// This calls the plugin directly rather than going through `MediaToolkit`.
/// Nothing the app does needs to synthesise audio, and an interface method that
/// exists only for tests is an interface method somebody will eventually call
/// in production.
Future<void> generateFixture(String destination) async {
  final session = await FFmpegKit.executeWithArguments([
    '-hide_banner',
    '-loglevel',
    'error',
    '-y',
    '-f',
    'lavfi',
    '-i',
    'sine=frequency=440:sample_rate=44100:duration=20',
    '-ac',
    '2',
    '-c:a',
    'libmp3lame',
    '-b:a',
    '128k',
    destination,
  ]);
  if (!File(destination).existsSync()) {
    throw StateError(
      'could not generate the fixture: ${await session.getOutput()}',
    );
  }
}
