import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import 'package:myapps_ai_online/myapps_ai_online.dart' as shared;
import 'package:myapps_ai_online_ui/myapps_ai_online_ui.dart';
import 'package:myapps_ai_core/myapps_ai_core.dart';
import 'package:myapps_data/myapps_data.dart';

import '../../../app/data_modules.dart';
import '../../jobs/services/job_store.dart';
import '../models/provider_config.dart';
import '../models/model_config.dart';
import '../../secrets/services/secrets_store.dart';
import 'settings_repository.dart';
import 'shared_online_adapter.dart';

/// Adapts synced provider records to shared editing without changing record IDs.
class TranscribeOnlineSources extends ChangeNotifier
    implements OnlineSourcesController {
  /// Purpose: Bind repository. Inputs: repository, notice text. Returns: Controller.
  /// Side effects: None. Notes: Caller initializes before rendering.
  TranscribeOnlineSources(
    this.repository,
    this.sentDescription, {
    this.onSaved,
    http.Client Function()? clientFactory,
    Future<Set<String>> Function()? jobModelIds,
  }) : _clientFactory = clientFactory ?? http.Client.new,
       _jobModelIds = jobModelIds ?? _storedJobModelIds;
  final SettingsRepository repository;
  final String sentDescription;
  final VoidCallback? onSaved;
  final http.Client Function() _clientFactory;
  final Future<Set<String>> Function() _jobModelIds;
  List<ProviderConfig> _records = [];
  final Map<String, shared.OnlineProvider> _drafts = {};
  SettingsLibrary? _library;

  /// Purpose: Reload records. Inputs: None. Returns: Completion.
  /// Side effects: Reads settings and notifies. Notes: Keeps template ownership in app.
  Future<void> reload() async {
    _library = await repository.load();
    _records = _library!.providers;
    if (!_disposed) notifyListeners();
  }

  bool _disposed = false;

  /// Purpose: End observations. Inputs: None. Returns: None.
  /// Side effects: Releases listeners. Notes: Pending reloads cannot notify after disposal.
  @override
  void dispose() {
    _disposed = true;
    super.dispose();
  }

  /// Purpose: List providers. Inputs: None. Returns: Providers.
  /// Side effects: None. Notes: Endpoint/auth fields only.
  @override
  List<shared.OnlineProvider> get providers => [
    for (final record in _records)
      onlineProvider(record).copyWith(
        modelId: _library?.model(record.defaultModelId)?.modelName,
        models: [
          for (final m
              in _library?.modelsOf(record.id) ?? const <ModelConfig>[])
            shared.OnlineModel(
              modelName: m.modelName,
              alias: m.displayName != m.modelName ? m.displayName : null,
              origin: shared.OnlineModelOrigin.manual,
            ),
        ],
      ),
  ];

  /// Purpose: Observe state. Inputs: None. Returns: Listenable.
  /// Side effects: None. Notes: None.
  @override
  Listenable get changes => this;

  /// Purpose: Register protocol presets. Inputs: None. Returns: Registry.
  /// Side effects: None. Notes: New IDs are generated by application repository.
  @override
  shared.OnlineProviderTemplateRegistry get templates =>
      shared.OnlineProviderTemplateRegistry.builtIn();

  /// Purpose: Allocate record ID. Inputs: None. Returns: ID.
  /// Side effects: None. Notes: Shipped template IDs unchanged.
  @override
  String newProviderId() => repository.newProviderId();

  /// Purpose: Check saved key. Inputs: providerId. Returns: Presence.
  /// Side effects: Reads secrets. Notes: Does not expose the key.
  @override
  Future<bool> hasKey(String providerId) async =>
      (await SecretsStore.keyFor(providerId))?.isNotEmpty ?? false;

  /// Purpose: Convert draft to app record. Inputs: draft. Returns: Record.
  /// Side effects: None. Notes: Preserves limits, templates, overrides, unknown fields.
  ProviderConfig _record(shared.OnlineProvider draft) {
    final previous = _records.where((item) => item.id == draft.id).firstOrNull;
    return (previous ??
            ProviderConfig(
              id: draft.id,
              name: draft.name,
              dialect: ProviderDialect.values.byName(draft.dialect.name),
              baseUrl: draft.baseUrl,
            ))
        .copyWith(
          name: draft.name,
          baseUrl: draft.baseUrl,
          dialect: ProviderDialect.values.byName(draft.dialect.name),
          extraHeaders: draft.headers,
          requestTimeoutSeconds: draft.requestTimeoutSeconds,
          authScheme: AuthScheme.values.byName(draft.authScheme.name),
          authHeaderName: draft.authHeaderName,
          clearAuthHeaderName: draft.authHeaderName == null,
        );
  }

  /// Purpose: Save provider, its model records and key. Inputs: provider,
  /// newKey, clearKey. Returns: Completion. Side effects: Writes records and
  /// secrets. Notes: Shared editor obtains privacy acknowledgement first.
  /// New models get unknown capabilities; existing records only change their
  /// display name. Removed models are deleted only when nothing refers to them.
  @override
  Future<void> save(
    shared.OnlineProvider provider, {
    String? newKey,
    bool clearKey = false,
  }) async {
    var record = _record(provider);
    final models = provider.models;
    final defaultName = (provider.modelId?.isNotEmpty ?? false)
        ? provider.modelId
        : models.firstOrNull?.modelName;
    if (models.isNotEmpty || (defaultName?.isNotEmpty ?? false)) {
      final library = await repository.load();
      final existingRecords = library.modelsOf(provider.id);
      final wanted = [
        ...models,
        if (defaultName != null &&
            !models.any((m) => m.modelName == defaultName))
          shared.OnlineModel(modelName: defaultName),
      ];
      String? defaultId;
      var providerSaved = false;
      for (final model in wanted) {
        final display = model.alias?.trim().isNotEmpty ?? false
            ? model.alias!.trim()
            : model.modelName;
        final existing = existingRecords
            .where((item) => item.modelName == model.modelName)
            .firstOrNull;
        if (existing == null) {
          if (!providerSaved) {
            await repository.saveProvider(record);
            providerSaved = true;
          }
          final created = ModelConfig(
            id: repository.newModelId(),
            providerId: provider.id,
            modelName: model.modelName,
            displayName: display,
          );
          await repository.saveModel(created);
          if (model.modelName == defaultName) defaultId = created.id;
        } else {
          if (existing.displayName != display) {
            await repository.saveModel(existing.copyWith(displayName: display));
          }
          if (model.modelName == defaultName) defaultId = existing.id;
        }
      }
      if (defaultId != null) {
        record = record.copyWith(defaultModelId: defaultId);
      }
      await _removeDropped(
        library,
        existingRecords,
        {for (final m in wanted) m.modelName},
        defaultId ?? record.defaultModelId,
        provider.id,
      );
    }
    await repository.saveProvider(record);
    if (clearKey || newKey != null) {
      await SecretsStore.setKey(provider.id, clearKey ? null : newKey);
    }
    await reload();
    onSaved?.call();
  }

  /// Purpose: Delete records of models removed in the editor. Inputs: library,
  /// the provider's earlier records, kept names, default id, provider id.
  /// Returns: Completion. Side effects: Deletes model records.
  /// Notes: Keeps the default, the app default selection, and any model a job
  /// still refers to; if jobs cannot be read nothing is deleted.
  Future<void> _removeDropped(
    SettingsLibrary library,
    List<ModelConfig> previous,
    Set<String> keptNames,
    String? defaultId,
    String providerId,
  ) async {
    final dropped = [
      for (final m in previous)
        if (!keptNames.contains(m.modelName) &&
            m.id != defaultId &&
            m.id != library.defaults.modelId)
          m,
    ];
    if (dropped.isEmpty) return;
    final Set<String> used;
    try {
      used = await _jobModelIds();
    } catch (_) {
      return;
    }
    for (final m in dropped) {
      if (!used.contains(m.id)) await repository.deleteModel(m.id);
    }
  }

  static Future<Set<String>> _storedJobModelIds() async => {
    for (final job in await JobStore.loadAll()) job.modelId,
  };

  /// Purpose: List a draft's models. Inputs: draft, draftKey. Returns: Entries.
  /// Side effects: One GET models. Notes: Only transcription models are
  /// marked chat so the picker shows them by default.
  @override
  Future<List<shared.OnlineModelEntry>> fetchModels(
    shared.OnlineProvider draft,
    String? draftKey,
  ) async {
    final client = _clientFactory();
    try {
      final entries = await shared.fetchOnlineModels(
        client,
        draft,
        apiKey: draftKey ?? await SecretsStore.keyFor(draft.id),
        path: draft.dialect == shared.OnlineDialect.openrouter
            ? 'models?output_modalities=transcription'
            : 'models',
      );
      return [
        for (final e in entries)
          shared.OnlineModelEntry(
            e.id,
            displayName: e.displayName,
            vendor: e.vendor,
            contextTokens: e.contextTokens,
            inputModalities: e.inputModalities,
            chat: _asrId.hasMatch(e.id),
          ),
      ];
    } finally {
      client.close();
    }
  }

  static final _asrId = RegExp(
    'whisper|transcribe|asr|stt|speech-to-text|parakeet|sensevoice|paraformer',
    caseSensitive: false,
  );

  /// Purpose: Built-in catalog models. Inputs: provider. Returns: Empty.
  /// Side effects: None. Notes: This app ships no chat model catalog.
  @override
  List<shared.OnlineModelEntry> catalogModels(shared.OnlineProvider provider) =>
      const [];

  /// Purpose: Delete source and key. Inputs: providerId. Returns: Completion.
  /// Side effects: Writes tombstone and settings. Notes: Job history is retained.
  @override
  Future<void> remove(String providerId) async {
    await SecretsStore.setKey(providerId, null);
    await repository.deleteProvider(providerId);
    await reload();
    onSaved?.call();
  }

  /// Purpose: Test endpoint explicitly. Inputs: draft, draftKey. Returns: Status.
  /// Side effects: GET models. Notes: No audio or prompts are sent.
  @override
  Future<GenAiStatusReport> testConnection(
    shared.OnlineProvider draft,
    String? draftKey,
  ) async {
    final acknowledgement = await _consentForDraft(draft).load();
    if (needsAcknowledgement(acknowledgement, 1)) {
      return const GenAiStatusReport(GenAiStatus.unavailable);
    }
    final client = http.Client();
    try {
      await shared.fetchOnlineModels(
        client,
        draft,
        apiKey: draftKey ?? await SecretsStore.keyFor(draft.id),
        path: draft.dialect == shared.OnlineDialect.openrouter
            ? 'models?output_modalities=transcription'
            : 'models',
      );
      return const GenAiStatusReport(GenAiStatus.available);
    } catch (_) {
      return const GenAiStatusReport(GenAiStatus.unavailable);
    } finally {
      client.close();
    }
  }

  /// Purpose: Describe sent data. Inputs: provider. Returns: Notice.
  /// Side effects: Remembers draft host for consent. Notes: No network.
  @override
  shared.OnlinePrivacyNotice? privacyNotice(shared.OnlineProvider provider) {
    _drafts[provider.id] = provider;
    return shared.OnlinePrivacyNotice.forProvider(
      version: 1,
      host: provider.recipientHost,
      providerName: provider.name,
      sent: [
        shared.OnlineDataItem(
          shared.OnlineDataCategory.audio,
          description: sentDescription,
        ),
      ],
    );
  }

  /// Purpose: Locate consent. Inputs: id. Returns: Store.
  /// Side effects: None. Notes: Same keys as online job gate.
  WebDavPrivacyAcknowledgementStore _consent(String id) {
    final provider =
        _drafts[id] ?? providers.firstWhere((item) => item.id == id);
    return _consentForDraft(provider);
  }

  /// Purpose: Locate draft permission. Inputs: provider. Returns: Store.
  /// Side effects: None. Notes: Never uses a different saved host's permission.
  WebDavPrivacyAcknowledgementStore _consentForDraft(
    shared.OnlineProvider provider,
  ) {
    final id = provider.id;
    final uri = Uri.tryParse(provider.baseUrl);
    return WebDavPrivacyAcknowledgementStore.storageConfig(
      const TranscribeStorageAdapter(),
      key:
          'onlineTranscriptionPrivacy:$id:${uri != null && uri.hasScheme && uri.hasAuthority ? uri.origin : provider.baseUrl}',
    );
  }

  /// Purpose: Read device consent. Inputs: providerId. Returns: Acknowledgement.
  /// Side effects: Reads config. Notes: Never synced.
  @override
  Future<shared.OnlinePrivacyAcknowledgement?> acknowledgement(
    String providerId,
  ) async {
    final record = await _consent(providerId).load();
    final host =
        (_drafts[providerId] ??
                providers.firstWhere((item) => item.id == providerId))
            .recipientHost;
    return record == null || host == null
        ? null
        : shared.OnlinePrivacyAcknowledgement(
            noticeVersion: record.noticeVersion,
            recipientHost: host,
            acknowledgedAt: record.acknowledgedAt,
          );
  }

  /// Purpose: Record device consent. Inputs: providerId, record. Returns: Completion.
  /// Side effects: Writes config. Notes: Stored independently of synced settings.
  @override
  Future<void> acknowledge(
    String providerId,
    shared.OnlinePrivacyAcknowledgement record,
  ) => _consent(providerId).acknowledge(record.noticeVersion);
}
