import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import 'package:myapps_ai_online/myapps_ai_online.dart' as shared;
import 'package:myapps_ai_online_ui/myapps_ai_online_ui.dart';
import 'package:myapps_ai_core/myapps_ai_core.dart';
import 'package:myapps_data/myapps_data.dart';

import '../../../app/data_modules.dart';
import '../models/provider_config.dart';
import '../models/model_config.dart';
import '../../secrets/services/secrets_store.dart';
import 'settings_repository.dart';
import 'shared_online_adapter.dart';

/// Adapts synced provider records to shared editing without changing record IDs.
class TranscribeOnlineSources extends ChangeNotifier
    implements OnlineSourcesController {
  /// Purpose: Bind repository. Inputs: repository, notice text. Returns: Controller.
  /// Side effects: None. Notes: Caller initializes before rendering.
  TranscribeOnlineSources(
    this.repository,
    this.sentDescription, {
    this.onSaved,
  });
  final SettingsRepository repository;
  final String sentDescription;
  final VoidCallback? onSaved;
  List<ProviderConfig> _records = [];
  final Map<String, shared.OnlineProvider> _drafts = {};
  SettingsLibrary? _library;

  /// Purpose: Reload records. Inputs: None. Returns: Completion.
  /// Side effects: Reads settings and notifies. Notes: Keeps template ownership in app.
  Future<void> reload() async {
    _library = await repository.load();
    _records = _library!.providers;
    if (!_disposed) notifyListeners();
  }

  bool _disposed = false;

  /// Purpose: End observations. Inputs: None. Returns: None.
  /// Side effects: Releases listeners. Notes: Pending reloads cannot notify after disposal.
  @override
  void dispose() {
    _disposed = true;
    super.dispose();
  }

  /// Purpose: List providers. Inputs: None. Returns: Providers.
  /// Side effects: None. Notes: Endpoint/auth fields only.
  @override
  List<shared.OnlineProvider> get providers => [
    for (final record in _records)
      onlineProvider(
        record,
      ).copyWith(modelId: _library?.model(record.defaultModelId)?.modelName),
  ];

  /// Purpose: Observe state. Inputs: None. Returns: Listenable.
  /// Side effects: None. Notes: None.
  @override
  Listenable get changes => this;

  /// Purpose: Register protocol presets. Inputs: None. Returns: Registry.
  /// Side effects: None. Notes: New IDs are generated by application repository.
  @override
  shared.OnlineProviderTemplateRegistry get templates =>
      shared.OnlineProviderTemplateRegistry.builtIn();

  /// Purpose: Allocate record ID. Inputs: None. Returns: ID.
  /// Side effects: None. Notes: Shipped template IDs unchanged.
  @override
  String newProviderId() => repository.newProviderId();

  /// Purpose: Check saved key. Inputs: providerId. Returns: Presence.
  /// Side effects: Reads secrets. Notes: Does not expose the key.
  @override
  Future<bool> hasKey(String providerId) async =>
      (await SecretsStore.keyFor(providerId))?.isNotEmpty ?? false;

  /// Purpose: Convert draft to app record. Inputs: draft. Returns: Record.
  /// Side effects: None. Notes: Preserves limits, templates, overrides, unknown fields.
  ProviderConfig _record(shared.OnlineProvider draft) {
    final previous = _records.where((item) => item.id == draft.id).firstOrNull;
    return (previous ??
            ProviderConfig(
              id: draft.id,
              name: draft.name,
              dialect: ProviderDialect.values.byName(draft.dialect.name),
              baseUrl: draft.baseUrl,
            ))
        .copyWith(
          name: draft.name,
          baseUrl: draft.baseUrl,
          dialect: ProviderDialect.values.byName(draft.dialect.name),
          extraHeaders: draft.headers,
          requestTimeoutSeconds: draft.requestTimeoutSeconds,
          authScheme: AuthScheme.values.byName(draft.authScheme.name),
          authHeaderName: draft.authHeaderName,
          clearAuthHeaderName: draft.authHeaderName == null,
        );
  }

  /// Purpose: Save provider and key. Inputs: provider, newKey, clearKey.
  /// Returns: Completion. Side effects: Writes records and secrets.
  /// Notes: Shared editor obtains privacy acknowledgement first.
  @override
  Future<void> save(
    shared.OnlineProvider provider, {
    String? newKey,
    bool clearKey = false,
  }) async {
    var record = _record(provider);
    if (provider.modelId?.isNotEmpty ?? false) {
      final library = await repository.load();
      final existing = library
          .modelsOf(provider.id)
          .where((model) => model.modelName == provider.modelId)
          .firstOrNull;
      final id = existing?.id ?? repository.newModelId();
      if (existing == null) {
        await repository.saveProvider(record);
        await repository.saveModel(
          ModelConfig(
            id: id,
            providerId: provider.id,
            modelName: provider.modelId!,
            displayName: provider.modelId!,
          ),
        );
      }
      record = record.copyWith(defaultModelId: id);
    }
    await repository.saveProvider(record);
    if (clearKey || newKey != null) {
      await SecretsStore.setKey(provider.id, clearKey ? null : newKey);
    }
    await reload();
    onSaved?.call();
  }

  /// Purpose: Delete source and key. Inputs: providerId. Returns: Completion.
  /// Side effects: Writes tombstone and settings. Notes: Job history is retained.
  @override
  Future<void> remove(String providerId) async {
    await SecretsStore.setKey(providerId, null);
    await repository.deleteProvider(providerId);
    await reload();
    onSaved?.call();
  }

  /// Purpose: Test endpoint explicitly. Inputs: draft, draftKey. Returns: Status.
  /// Side effects: GET models. Notes: No audio or prompts are sent.
  @override
  Future<GenAiStatusReport> testConnection(
    shared.OnlineProvider draft,
    String? draftKey,
  ) async {
    final acknowledgement = await _consentForDraft(draft).load();
    if (needsAcknowledgement(acknowledgement, 1)) {
      return const GenAiStatusReport(GenAiStatus.unavailable);
    }
    final client = http.Client();
    try {
      await shared.fetchOnlineModels(
        client,
        draft,
        apiKey: draftKey ?? await SecretsStore.keyFor(draft.id),
        path: draft.dialect == shared.OnlineDialect.openrouter
            ? 'models?output_modalities=transcription'
            : 'models',
      );
      return const GenAiStatusReport(GenAiStatus.available);
    } catch (_) {
      return const GenAiStatusReport(GenAiStatus.unavailable);
    } finally {
      client.close();
    }
  }

  /// Purpose: Describe sent data. Inputs: provider. Returns: Notice.
  /// Side effects: Remembers draft host for consent. Notes: No network.
  @override
  shared.OnlinePrivacyNotice? privacyNotice(shared.OnlineProvider provider) {
    _drafts[provider.id] = provider;
    return shared.OnlinePrivacyNotice.forProvider(
      version: 1,
      host: provider.recipientHost,
      providerName: provider.name,
      sent: [
        shared.OnlineDataItem(
          shared.OnlineDataCategory.audio,
          description: sentDescription,
        ),
      ],
    );
  }

  /// Purpose: Locate consent. Inputs: id. Returns: Store.
  /// Side effects: None. Notes: Same keys as online job gate.
  WebDavPrivacyAcknowledgementStore _consent(String id) {
    final provider =
        _drafts[id] ?? providers.firstWhere((item) => item.id == id);
    return _consentForDraft(provider);
  }

  /// Purpose: Locate draft permission. Inputs: provider. Returns: Store.
  /// Side effects: None. Notes: Never uses a different saved host's permission.
  WebDavPrivacyAcknowledgementStore _consentForDraft(
    shared.OnlineProvider provider,
  ) {
    final id = provider.id;
    final uri = Uri.tryParse(provider.baseUrl);
    return WebDavPrivacyAcknowledgementStore.storageConfig(
      const TranscribeStorageAdapter(),
      key:
          'onlineTranscriptionPrivacy:$id:${uri != null && uri.hasScheme && uri.hasAuthority ? uri.origin : provider.baseUrl}',
    );
  }

  /// Purpose: Read device consent. Inputs: providerId. Returns: Acknowledgement.
  /// Side effects: Reads config. Notes: Never synced.
  @override
  Future<shared.OnlinePrivacyAcknowledgement?> acknowledgement(
    String providerId,
  ) async {
    final record = await _consent(providerId).load();
    final host =
        (_drafts[providerId] ??
                providers.firstWhere((item) => item.id == providerId))
            .recipientHost;
    return record == null || host == null
        ? null
        : shared.OnlinePrivacyAcknowledgement(
            noticeVersion: record.noticeVersion,
            recipientHost: host,
            acknowledgedAt: record.acknowledgedAt,
          );
  }

  /// Purpose: Record device consent. Inputs: providerId, record. Returns: Completion.
  /// Side effects: Writes config. Notes: Stored independently of synced settings.
  @override
  Future<void> acknowledge(
    String providerId,
    shared.OnlinePrivacyAcknowledgement record,
  ) => _consent(providerId).acknowledge(record.noticeVersion);
}
