/// Purpose: Regenerate the Dart bindings from the vendored whisper.cpp headers.
/// Inputs: Optionally the path to `libclang` as the first argument; otherwise
/// Visual Studio's LLVM component on Windows, then ffigen's default places.
/// Returns: None.
/// Side effects: Rewrites `lib/src/whisper_bindings.g.dart` and
/// `lib/src/ggml_bindings.g.dart`.
/// Notes: Run after the headers in `third_party/whisper.cpp/include/` change,
/// which happens only when `native/binaries.json` moves to a new upstream
/// version — the bindings must describe exactly the version the binaries were
/// built from (decision D21 of the local-models plan). Run from this package:
/// `dart run tool/ffigen.dart`.
library;

import 'dart:ffi' show Abi;
import 'dart:io';

import 'package:ffigen/ffigen.dart';

/// The whisper.cpp entry points the app uses; everything they reference comes
/// along, so the parameter structs are generated from the header.
const _whisperFunctions = {
  'whisper_version',
  'whisper_print_system_info',
  'whisper_log_set',
  'whisper_context_default_params',
  'whisper_init_from_file_with_params',
  'whisper_free',
  'whisper_full_default_params',
  'whisper_full',
  'whisper_full_n_segments',
  'whisper_full_get_segment_t0',
  'whisper_full_get_segment_t1',
  'whisper_full_get_segment_text',
  'whisper_full_lang_id',
  'whisper_lang_str',
};

/// The ggml entry points: backend loading, the device list, logging. They
/// live in the ggml libraries beside whisper's, or inside whisper's own binary
/// on Apple, so they are looked up at run time rather than bound to an asset.
const _ggmlFunctions = {
  'ggml_log_set',
  'ggml_backend_load_all_from_path',
  'ggml_backend_reg_count',
  'ggml_backend_dev_count',
  'ggml_backend_dev_get',
  'ggml_backend_dev_name',
  'ggml_backend_dev_description',
  'ggml_backend_dev_type',
};

/// Purpose: Generate both binding files.
/// Inputs: [args], optionally the libclang path.
/// Returns: None.
/// Side effects: Writes the two generated files.
/// Notes: None.
Future<void> main(List<String> args) async {
  final root = Platform.script.resolve('../');
  final include = root.resolve('third_party/whisper.cpp/include/');
  final libclang = args.isNotEmpty ? args.first : _visualStudioLibclang();
  const preamble =
      '// Generated by tool/ffigen.dart from the vendored whisper.cpp\n'
      '// headers (third_party/whisper.cpp). Do not edit by hand.\n'
      '// ignore_for_file: type=lint';

  Input input(String header) => Input(
    entryPoints: [include.resolve(header)],
    compilerOptions: ['-I${include.toFilePath()}'],
  );

  await FfiGenerator(
    input: input('whisper.h'),
    output: Output(
      dart: DartOutput(path: root.resolve('lib/src/whisper_bindings.g.dart')),
      preamble: preamble,
      style: const NativeExternalBindings(
        assetId: 'package:local_asr_whisper/whisper',
      ),
    ),
    visitors: [
      Visitor(func: (f) => f.isIncluded = _whisperFunctions.contains(f.name)),
    ],
  ).generate(libclangDylib: libclang == null ? null : Uri.file(libclang));

  await FfiGenerator(
    input: input('ggml-backend.h'),
    output: Output(
      dart: DartOutput(path: root.resolve('lib/src/ggml_bindings.g.dart')),
      preamble: preamble,
      style: const DynamicLibraryBindings(
        wrapperName: 'GgmlBindings',
        wrapperDocComment:
            'The ggml functions the app calls, looked up in '
            'whichever loaded library exports them.',
      ),
    ),
    visitors: [
      Visitor(func: (f) => f.isIncluded = _ggmlFunctions.contains(f.name)),
    ],
  ).generate(libclangDylib: libclang == null ? null : Uri.file(libclang));
}

/// Purpose: Find libclang in Visual Studio's LLVM component.
/// Inputs: None.
/// Returns: Its path, or null to let ffigen search its default places.
/// Side effects: Runs `vswhere` on Windows.
/// Notes: The component matches the host: ARM64 on an ARM64 machine.
String? _visualStudioLibclang() {
  if (!Platform.isWindows) return null;
  final vswhere =
      '${Platform.environment['ProgramFiles(x86)']}\\Microsoft Visual Studio\\Installer\\vswhere.exe';
  if (!File(vswhere).existsSync()) return null;
  final result = Process.runSync(vswhere, [
    '-latest',
    '-property',
    'installationPath',
  ]);
  final vs = '${result.stdout}'.trim();
  final arch = Abi.current() == Abi.windowsArm64 ? 'ARM64' : 'x64';
  final dll = '$vs\\VC\\Tools\\Llvm\\$arch\\bin\\libclang.dll';
  return File(dll).existsSync() ? dll : null;
}
