/// Purpose: Regenerate the Dart bindings from the bridge's C header.
/// Inputs: Optionally the path to `libclang` as the first argument; otherwise
/// Visual Studio's LLVM component on Windows, then ffigen's default places.
/// Returns: None.
/// Side effects: Rewrites `lib/src/apple_bindings.g.dart`.
/// Notes: Run after `bridge/lasr_apple.h` changes, together with a new
/// `apple-prebuild.yml` release and its hash in `native/binaries.json`. Run
/// from this package: `dart run tool/ffigen.dart`.
library;

import 'dart:ffi' show Abi;
import 'dart:io';

import 'package:ffigen/ffigen.dart';

/// Purpose: Generate the binding file.
/// Inputs: [args], optionally the libclang path.
/// Returns: None.
/// Side effects: Writes the generated file.
/// Notes: None.
Future<void> main(List<String> args) async {
  final root = Platform.script.resolve('../');
  final libclang = args.isNotEmpty ? args.first : _visualStudioLibclang();
  await FfiGenerator(
    input: Input(entryPoints: [root.resolve('bridge/lasr_apple.h')]),
    output: Output(
      dart: DartOutput(path: root.resolve('lib/src/apple_bindings.g.dart')),
      preamble:
          '// Generated by tool/ffigen.dart from bridge/lasr_apple.h. Do not\n'
          '// edit by hand.\n'
          '// ignore_for_file: type=lint',
      style: const NativeExternalBindings(
        assetId: 'package:local_asr_apple/lasr_apple',
      ),
    ),
    visitors: [Visitor(func: (f) => f.isIncluded = f.name.startsWith('lasr_'))],
  ).generate(libclangDylib: libclang == null ? null : Uri.file(libclang));
}

/// Purpose: Find libclang in Visual Studio's LLVM component.
/// Inputs: None.
/// Returns: Its path, or null to let ffigen search its default places.
/// Side effects: Runs `vswhere` on Windows.
/// Notes: The component matches the host: ARM64 on an ARM64 machine.
String? _visualStudioLibclang() {
  if (!Platform.isWindows) return null;
  final vswhere =
      '${Platform.environment['ProgramFiles(x86)']}\\Microsoft Visual Studio\\Installer\\vswhere.exe';
  if (!File(vswhere).existsSync()) return null;
  final result = Process.runSync(vswhere, [
    '-latest',
    '-property',
    'installationPath',
  ]);
  final vs = '${result.stdout}'.trim();
  final arch = Abi.current() == Abi.windowsArm64 ? 'ARM64' : 'x64';
  final dll = '$vs\\VC\\Tools\\Llvm\\$arch\\bin\\libclang.dll';
  return File(dll).existsSync() ? dll : null;
}
