// Generated by tool/ffigen.dart from the vendored sherpa-onnx
// header (third_party/sherpa-onnx). Do not edit by hand.
// ignore_for_file: type=lint
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
@ffi.DefaultAsset('package:local_asr_sherpa/sherpa')
library;

import 'dart:ffi' as ffi;

/// @brief Provide the full utterance to an offline ASR stream.
///
/// The input is mono floating-point PCM normalized to the range [-1, 1].
/// If @p sample_rate differs from the recognizer feature sample rate,
/// sherpa-onnx resamples internally.
///
/// @warning Call this function at most once for each offline stream. Offline
/// recognition expects the entire utterance in a single call.
///
/// @param stream A pointer returned by SherpaOnnxCreateOfflineStream().
/// @param sample_rate Sample rate of @p samples.
/// @param samples Pointer to @p n samples in the range [-1, 1].
/// @param n Number of samples.
///
/// @code
/// const SherpaOnnxWave *wave =
/// SherpaOnnxReadWave("./sherpa-onnx-whisper-tiny.en/test_wavs/0.wav");
/// const SherpaOnnxOfflineStream *stream =
/// SherpaOnnxCreateOfflineStream(recognizer);
/// SherpaOnnxAcceptWaveformOffline(stream, wave->sample_rate,
/// wave->samples, wave->num_samples);
/// SherpaOnnxDecodeOfflineStream(recognizer, stream);
/// @endcode
/// @see SherpaOnnxCreateOfflineStream, SherpaOnnxDecodeOfflineStream
@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<SherpaOnnxOfflineStream>,
    ffi.Int32,
    ffi.Pointer<ffi.Float>,
    ffi.Int32,
  )
>()
external void SherpaOnnxAcceptWaveformOffline(
  ffi.Pointer<SherpaOnnxOfflineStream> stream,
  int sample_rate,
  ffi.Pointer<ffi.Float> samples,
  int n,
);

/// @brief Create a non-streaming ASR recognizer.
///
/// @param config Recognizer configuration.
/// @return A recognizer handle on success, or NULL if the configuration is
/// invalid. The caller owns the returned object and must free it with
/// SherpaOnnxDestroyOfflineRecognizer().
///
/// Whisper example:
///
/// @code
/// SherpaOnnxOfflineRecognizerConfig config;
/// memset(&config, 0, sizeof(config));
/// config.feat_config.sample_rate = 16000;
/// config.feat_config.feature_dim = 80;
/// config.model_config.whisper.encoder =
/// "./sherpa-onnx-whisper-tiny/tiny-encoder.onnx";
/// config.model_config.whisper.decoder =
/// "./sherpa-onnx-whisper-tiny/tiny-decoder.onnx";
/// config.model_config.whisper.language = "en";
/// config.model_config.whisper.task = "transcribe";
/// config.model_config.tokens =
/// "./sherpa-onnx-whisper-tiny/tiny-tokens.txt";
/// config.model_config.provider = "cpu";
/// config.model_config.num_threads = 1;
/// config.decoding_method = "greedy_search";
///
/// const SherpaOnnxOfflineRecognizer *recognizer =
/// SherpaOnnxCreateOfflineRecognizer(&config);
/// @endcode
///
/// SenseVoice example:
///
/// @code
/// config.model_config.sense_voice.model =
/// "./sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8/model.int8.onnx";
/// config.model_config.sense_voice.language = "auto";
/// config.model_config.sense_voice.use_itn = 1;
/// config.model_config.tokens =
/// "./sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8/tokens.txt";
/// @endcode
///
/// Parakeet TDT example:
///
/// @code
/// config.model_config.transducer.encoder =
/// "./sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8/encoder.int8.onnx";
/// config.model_config.transducer.decoder =
/// "./sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8/decoder.int8.onnx";
/// config.model_config.transducer.joiner =
/// "./sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8/joiner.int8.onnx";
/// config.model_config.tokens =
/// "./sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8/tokens.txt";
/// config.model_config.model_type = "nemo_transducer";
/// @endcode
/// @see SherpaOnnxOfflineRecognizerConfig, SherpaOnnxDestroyOfflineRecognizer
@ffi.Native<
  ffi.Pointer<SherpaOnnxOfflineRecognizer> Function(
    ffi.Pointer<SherpaOnnxOfflineRecognizerConfig>,
  )
>()
external ffi.Pointer<SherpaOnnxOfflineRecognizer>
SherpaOnnxCreateOfflineRecognizer(
  ffi.Pointer<SherpaOnnxOfflineRecognizerConfig> config,
);

/// @brief Create an offline speaker diarization pipeline.
///
/// @param config Offline speaker diarization configuration.
/// @return A newly allocated diarizer on success, or NULL on error. Free it
/// with SherpaOnnxDestroyOfflineSpeakerDiarization().
/// @see SherpaOnnxDestroyOfflineSpeakerDiarization
@ffi.Native<
  ffi.Pointer<SherpaOnnxOfflineSpeakerDiarization> Function(
    ffi.Pointer<SherpaOnnxOfflineSpeakerDiarizationConfig>,
  )
>()
external ffi.Pointer<SherpaOnnxOfflineSpeakerDiarization>
SherpaOnnxCreateOfflineSpeakerDiarization(
  ffi.Pointer<SherpaOnnxOfflineSpeakerDiarizationConfig> config,
);

/// @brief Create a non-streaming ASR input stream.
///
/// @param recognizer A pointer returned by SherpaOnnxCreateOfflineRecognizer().
/// @return A newly created stream. The caller owns the returned object and must
/// free it with SherpaOnnxDestroyOfflineStream().
///
/// @code
/// const SherpaOnnxWave *wave =
/// SherpaOnnxReadWave("./sherpa-onnx-whisper-tiny.en/test_wavs/0.wav");
/// const SherpaOnnxOfflineStream *stream =
/// SherpaOnnxCreateOfflineStream(recognizer);
/// @endcode
/// @see SherpaOnnxDestroyOfflineStream, SherpaOnnxAcceptWaveformOffline
@ffi.Native<
  ffi.Pointer<SherpaOnnxOfflineStream> Function(
    ffi.Pointer<SherpaOnnxOfflineRecognizer>,
  )
>()
external ffi.Pointer<SherpaOnnxOfflineStream> SherpaOnnxCreateOfflineStream(
  ffi.Pointer<SherpaOnnxOfflineRecognizer> recognizer,
);

/// @brief Run offline ASR on one stream.
///
/// Call this after SherpaOnnxAcceptWaveformOffline().
///
/// @param recognizer A pointer returned by SherpaOnnxCreateOfflineRecognizer().
/// @param stream A pointer returned by SherpaOnnxCreateOfflineStream().
///
/// @code
/// SherpaOnnxDecodeOfflineStream(recognizer, stream);
/// @endcode
/// @see SherpaOnnxAcceptWaveformOffline, SherpaOnnxGetOfflineStreamResult
@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<SherpaOnnxOfflineRecognizer>,
    ffi.Pointer<SherpaOnnxOfflineStream>,
  )
>()
external void SherpaOnnxDecodeOfflineStream(
  ffi.Pointer<SherpaOnnxOfflineRecognizer> recognizer,
  ffi.Pointer<SherpaOnnxOfflineStream> stream,
);

/// @brief Destroy a non-streaming recognizer.
///
/// @param recognizer A pointer returned by SherpaOnnxCreateOfflineRecognizer().
///
/// @code
/// SherpaOnnxDestroyOfflineRecognizer(recognizer);
/// recognizer = NULL;
/// @endcode
/// @see SherpaOnnxCreateOfflineRecognizer
@ffi.Native<ffi.Void Function(ffi.Pointer<SherpaOnnxOfflineRecognizer>)>()
external void SherpaOnnxDestroyOfflineRecognizer(
  ffi.Pointer<SherpaOnnxOfflineRecognizer> recognizer,
);

/// @brief Destroy a result returned by SherpaOnnxGetOfflineStreamResult().
///
/// @param r A pointer returned by SherpaOnnxGetOfflineStreamResult().
///
/// @code
/// SherpaOnnxDestroyOfflineRecognizerResult(r);
/// r = NULL;
/// @endcode
/// @see SherpaOnnxGetOfflineStreamResult
@ffi.Native<ffi.Void Function(ffi.Pointer<SherpaOnnxOfflineRecognizerResult>)>()
external void SherpaOnnxDestroyOfflineRecognizerResult(
  ffi.Pointer<SherpaOnnxOfflineRecognizerResult> r,
);

/// @brief Destroy an offline speaker diarizer.
///
/// @param sd A pointer returned by SherpaOnnxCreateOfflineSpeakerDiarization().
/// @see SherpaOnnxCreateOfflineSpeakerDiarization
@ffi.Native<
  ffi.Void Function(ffi.Pointer<SherpaOnnxOfflineSpeakerDiarization>)
>()
external void SherpaOnnxDestroyOfflineSpeakerDiarization(
  ffi.Pointer<SherpaOnnxOfflineSpeakerDiarization> sd,
);

/// @brief Destroy a non-streaming ASR stream.
///
/// @param stream A pointer returned by SherpaOnnxCreateOfflineStream() or
/// SherpaOnnxCreateOfflineStreamWithHotwords().
///
/// @code
/// SherpaOnnxDestroyOfflineStream(stream);
/// stream = NULL;
/// @endcode
/// @see SherpaOnnxCreateOfflineStream
@ffi.Native<ffi.Void Function(ffi.Pointer<SherpaOnnxOfflineStream>)>()
external void SherpaOnnxDestroyOfflineStream(
  ffi.Pointer<SherpaOnnxOfflineStream> stream,
);

/// @brief Get the recognition result for an offline ASR stream.
///
/// Call this after SherpaOnnxDecodeOfflineStream() or
/// SherpaOnnxDecodeMultipleOfflineStreams().
///
/// @param stream A pointer returned by SherpaOnnxCreateOfflineStream().
/// @return A newly allocated result snapshot. Free it with
/// SherpaOnnxDestroyOfflineRecognizerResult().
///
/// @code
/// const SherpaOnnxOfflineRecognizerResult *r =
/// SherpaOnnxGetOfflineStreamResult(stream);
/// printf("%s\n", r->text);
/// if (r->timestamps) {
/// printf("First token starts at %.3f seconds\n", r->timestamps[0]);
/// }
/// SherpaOnnxDestroyOfflineRecognizerResult(r);
/// @endcode
/// @see SherpaOnnxDestroyOfflineRecognizerResult, SherpaOnnxDecodeOfflineStream
@ffi.Native<
  ffi.Pointer<SherpaOnnxOfflineRecognizerResult> Function(
    ffi.Pointer<SherpaOnnxOfflineStream>,
  )
>()
external ffi.Pointer<SherpaOnnxOfflineRecognizerResult>
SherpaOnnxGetOfflineStreamResult(ffi.Pointer<SherpaOnnxOfflineStream> stream);

/// @brief Return the sherpa-onnx version string.
///
/// The returned pointer refers to statically allocated memory owned by the
/// library. Do not free it and do not modify it.
///
/// @return Version string, for example `"1.12.1"`.
///
/// @code
/// printf("sherpa-onnx version: %s\n", SherpaOnnxGetVersionStr());
/// @endcode
@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> SherpaOnnxGetVersionStr();

/// @brief Destroy a diarization result.
///
/// @param r A pointer returned by one of the
/// SherpaOnnxOfflineSpeakerDiarizationProcess*() functions.
@ffi.Native<
  ffi.Void Function(ffi.Pointer<SherpaOnnxOfflineSpeakerDiarizationResult>)
>()
external void SherpaOnnxOfflineSpeakerDiarizationDestroyResult(
  ffi.Pointer<SherpaOnnxOfflineSpeakerDiarizationResult> r,
);

/// @brief Destroy a segment array returned by
/// SherpaOnnxOfflineSpeakerDiarizationResultSortByStartTime().
///
/// @param s A pointer returned by
/// SherpaOnnxOfflineSpeakerDiarizationResultSortByStartTime().
@ffi.Native<
  ffi.Void Function(ffi.Pointer<SherpaOnnxOfflineSpeakerDiarizationSegment>)
>()
external void SherpaOnnxOfflineSpeakerDiarizationDestroySegment(
  ffi.Pointer<SherpaOnnxOfflineSpeakerDiarizationSegment> s,
);

/// @brief Return the expected input sample rate.
///
/// @param sd A pointer returned by SherpaOnnxCreateOfflineSpeakerDiarization().
/// @return Required input sample rate in Hz.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<SherpaOnnxOfflineSpeakerDiarization>)
>()
external int SherpaOnnxOfflineSpeakerDiarizationGetSampleRate(
  ffi.Pointer<SherpaOnnxOfflineSpeakerDiarization> sd,
);

/// @brief Run offline speaker diarization.
///
/// @param sd A pointer returned by SherpaOnnxCreateOfflineSpeakerDiarization().
/// @param samples Input mono PCM samples normalized to [-1, 1].
/// @param n Number of input samples.
/// @return A newly allocated diarization result. Free it with
/// SherpaOnnxOfflineSpeakerDiarizationDestroyResult().
@ffi.Native<
  ffi.Pointer<SherpaOnnxOfflineSpeakerDiarizationResult> Function(
    ffi.Pointer<SherpaOnnxOfflineSpeakerDiarization>,
    ffi.Pointer<ffi.Float>,
    ffi.Int32,
  )
>()
external ffi.Pointer<SherpaOnnxOfflineSpeakerDiarizationResult>
SherpaOnnxOfflineSpeakerDiarizationProcess(
  ffi.Pointer<SherpaOnnxOfflineSpeakerDiarization> sd,
  ffi.Pointer<ffi.Float> samples,
  int n,
);

/// @brief Return the number of diarization segments.
///
/// @param r A pointer returned by one of the
/// SherpaOnnxOfflineSpeakerDiarizationProcess*() functions.
/// @return Number of segments.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<SherpaOnnxOfflineSpeakerDiarizationResult>)
>()
external int SherpaOnnxOfflineSpeakerDiarizationResultGetNumSegments(
  ffi.Pointer<SherpaOnnxOfflineSpeakerDiarizationResult> r,
);

/// @brief Return the number of speakers in a diarization result.
///
/// @param r A pointer returned by one of the
/// SherpaOnnxOfflineSpeakerDiarizationProcess*() functions.
/// @return Number of speaker clusters.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<SherpaOnnxOfflineSpeakerDiarizationResult>)
>()
external int SherpaOnnxOfflineSpeakerDiarizationResultGetNumSpeakers(
  ffi.Pointer<SherpaOnnxOfflineSpeakerDiarizationResult> r,
);

/// @brief Return segments sorted by start time.
///
/// The returned array contains exactly
/// SherpaOnnxOfflineSpeakerDiarizationResultGetNumSegments() entries.
///
/// @param r A pointer returned by one of the
/// SherpaOnnxOfflineSpeakerDiarizationProcess*() functions.
/// @return A newly allocated segment array. Free it with
/// SherpaOnnxOfflineSpeakerDiarizationDestroySegment().
@ffi.Native<
  ffi.Pointer<SherpaOnnxOfflineSpeakerDiarizationSegment> Function(
    ffi.Pointer<SherpaOnnxOfflineSpeakerDiarizationResult>,
  )
>()
external ffi.Pointer<SherpaOnnxOfflineSpeakerDiarizationSegment>
SherpaOnnxOfflineSpeakerDiarizationResultSortByStartTime(
  ffi.Pointer<SherpaOnnxOfflineSpeakerDiarizationResult> r,
);

/// @brief Fast clustering configuration.
///
/// If @c num_clusters is greater than 0, @c threshold is ignored. When the
/// number of speakers is known in advance, setting @c num_clusters is strongly
/// recommended.
final class SherpaOnnxFastClusteringConfig extends ffi.Struct {
  /// Known number of speakers. If > 0, threshold-based clustering is bypassed.
  @ffi.Int32()
  external int num_clusters;

  /// Distance threshold used when the number of speakers is unknown.
  @ffi.Float()
  external double threshold;

  /// When non-zero, per-segment confidence values are computed.
  @ffi.Int32()
  external int compute_confidence;

  static ffi.Pointer<SherpaOnnxFastClusteringConfig> $allocate(
    ffi.Allocator $allocator, {
    required int num_clusters,
    required double threshold,
    required int compute_confidence,
  }) => $allocator<SherpaOnnxFastClusteringConfig>()
    ..ref.num_clusters = num_clusters
    ..ref.threshold = threshold
    ..ref.compute_confidence = compute_confidence;
}

/// @brief Feature extraction settings for ASR.
///
/// The bundled ASR models typically expect 16 kHz mono audio and 80-bin
/// features.
final class SherpaOnnxFeatureConfig extends ffi.Struct {
  /// Sample rate expected by the model, for example 16000.
  @ffi.Int32()
  external int sample_rate;

  /// Feature dimension expected by the model, for example 80.
  @ffi.Int32()
  external int feature_dim;

  static ffi.Pointer<SherpaOnnxFeatureConfig> $allocate(
    ffi.Allocator $allocator, {
    required int sample_rate,
    required int feature_dim,
  }) => $allocator<SherpaOnnxFeatureConfig>()
    ..ref.sample_rate = sample_rate
    ..ref.feature_dim = feature_dim;
}

/// @brief Configuration for homophone replacement.
final class SherpaOnnxHomophoneReplacerConfig extends ffi.Struct {
  /// Unused legacy field kept for ABI compatibility.
  external ffi.Pointer<ffi.Char> dict_dir;

  /// Path to the lexicon used by the homophone replacer.
  external ffi.Pointer<ffi.Char> lexicon;

  /// Path to the replacement rule FST file.
  external ffi.Pointer<ffi.Char> rule_fsts;

  static ffi.Pointer<SherpaOnnxHomophoneReplacerConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> dict_dir,
    required ffi.Pointer<ffi.Char> lexicon,
    required ffi.Pointer<ffi.Char> rule_fsts,
  }) => $allocator<SherpaOnnxHomophoneReplacerConfig>()
    ..ref.dict_dir = dict_dir
    ..ref.lexicon = lexicon
    ..ref.rule_fsts = rule_fsts;
}

/// @brief Configuration for a Canary model.
final class SherpaOnnxOfflineCanaryModelConfig extends ffi.Struct {
  /// Path to the encoder ONNX model.
  external ffi.Pointer<ffi.Char> encoder;

  /// Path to the decoder ONNX model.
  external ffi.Pointer<ffi.Char> decoder;

  /// Source language hint.
  external ffi.Pointer<ffi.Char> src_lang;

  /// Target language hint.
  external ffi.Pointer<ffi.Char> tgt_lang;

  /// Non-zero to enable punctuation and capitalization when supported.
  @ffi.Int32()
  external int use_pnc;

  static ffi.Pointer<SherpaOnnxOfflineCanaryModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> encoder,
    required ffi.Pointer<ffi.Char> decoder,
    required ffi.Pointer<ffi.Char> src_lang,
    required ffi.Pointer<ffi.Char> tgt_lang,
    required int use_pnc,
  }) => $allocator<SherpaOnnxOfflineCanaryModelConfig>()
    ..ref.encoder = encoder
    ..ref.decoder = decoder
    ..ref.src_lang = src_lang
    ..ref.tgt_lang = tgt_lang
    ..ref.use_pnc = use_pnc;
}

/// @brief Configuration for a Cohere Transcribe model.
final class SherpaOnnxOfflineCohereTranscribeModelConfig extends ffi.Struct {
  /// Path to the encoder ONNX model.
  external ffi.Pointer<ffi.Char> encoder;

  /// Path to the decoder ONNX model.
  external ffi.Pointer<ffi.Char> decoder;

  /// Optional language hint, for example "en" or "zh".
  external ffi.Pointer<ffi.Char> language;

  /// Non-zero to enable punctuation.
  @ffi.Int32()
  external int use_punct;

  /// Non-zero to enable inverse text normalization.
  @ffi.Int32()
  external int use_itn;

  static ffi.Pointer<SherpaOnnxOfflineCohereTranscribeModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> encoder,
    required ffi.Pointer<ffi.Char> decoder,
    required ffi.Pointer<ffi.Char> language,
    required int use_punct,
    required int use_itn,
  }) => $allocator<SherpaOnnxOfflineCohereTranscribeModelConfig>()
    ..ref.encoder = encoder
    ..ref.decoder = decoder
    ..ref.language = language
    ..ref.use_punct = use_punct
    ..ref.use_itn = use_itn;
}

final class SherpaOnnxOfflineDiacritization extends ffi.Opaque {}

/// @brief Configuration for offline diacritization.
final class SherpaOnnxOfflineDiacritizationConfig extends ffi.Struct {
  /// Model configuration.
  external SherpaOnnxOfflineDiacritizationModelConfig model;
}

/// @brief Offline diacritization model configuration.
final class SherpaOnnxOfflineDiacritizationModelConfig extends ffi.Struct {
  /// Offline diacritization encoder model file.
  external ffi.Pointer<ffi.Char> catt_encoder;

  /// Offline diacritization decoder model file.
  external ffi.Pointer<ffi.Char> catt_decoder;

  /// Number of inference threads.
  @ffi.Int32()
  external int num_threads;

  /// Non-zero to print debug information.
  @ffi.Int32()
  external int debug;

  /// Execution provider such as `"cpu"`.
  external ffi.Pointer<ffi.Char> provider;

  static ffi.Pointer<SherpaOnnxOfflineDiacritizationModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> catt_encoder,
    required ffi.Pointer<ffi.Char> catt_decoder,
    required int num_threads,
    required int debug,
    required ffi.Pointer<ffi.Char> provider,
  }) => $allocator<SherpaOnnxOfflineDiacritizationModelConfig>()
    ..ref.catt_encoder = catt_encoder
    ..ref.catt_decoder = catt_decoder
    ..ref.num_threads = num_threads
    ..ref.debug = debug
    ..ref.provider = provider;
}

/// @brief Configuration for a Dolphin model.
final class SherpaOnnxOfflineDolphinModelConfig extends ffi.Struct {
  /// Path to the ONNX model.
  external ffi.Pointer<ffi.Char> model;

  static ffi.Pointer<SherpaOnnxOfflineDolphinModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> model,
  }) => $allocator<SherpaOnnxOfflineDolphinModelConfig>()..ref.model = model;
}

/// @brief Configuration for a FireRedAsr CTC model.
final class SherpaOnnxOfflineFireRedAsrCtcModelConfig extends ffi.Struct {
  /// Path to the ONNX model.
  external ffi.Pointer<ffi.Char> model;

  static ffi.Pointer<SherpaOnnxOfflineFireRedAsrCtcModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> model,
  }) =>
      $allocator<SherpaOnnxOfflineFireRedAsrCtcModelConfig>()
        ..ref.model = model;
}

/// @brief Configuration for a FireRedAsr encoder/decoder model.
final class SherpaOnnxOfflineFireRedAsrModelConfig extends ffi.Struct {
  /// Path to the encoder ONNX model.
  external ffi.Pointer<ffi.Char> encoder;

  /// Path to the decoder ONNX model.
  external ffi.Pointer<ffi.Char> decoder;

  static ffi.Pointer<SherpaOnnxOfflineFireRedAsrModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> encoder,
    required ffi.Pointer<ffi.Char> decoder,
  }) => $allocator<SherpaOnnxOfflineFireRedAsrModelConfig>()
    ..ref.encoder = encoder
    ..ref.decoder = decoder;
}

/// @brief Configuration for an offline FunASR Nano model.
final class SherpaOnnxOfflineFunASRNanoModelConfig extends ffi.Struct {
  /// Path to the encoder adaptor.
  external ffi.Pointer<ffi.Char> encoder_adaptor;

  /// Path to the LLM ONNX model.
  external ffi.Pointer<ffi.Char> llm;

  /// Path to the embedding model.
  external ffi.Pointer<ffi.Char> embedding;

  /// Path to the tokenizer file.
  external ffi.Pointer<ffi.Char> tokenizer;

  /// System prompt.
  external ffi.Pointer<ffi.Char> system_prompt;

  /// User prompt.
  external ffi.Pointer<ffi.Char> user_prompt;

  /// Maximum number of generated tokens.
  @ffi.Int32()
  external int max_new_tokens;

  /// Sampling temperature.
  @ffi.Float()
  external double temperature;

  /// Top-p sampling threshold.
  @ffi.Float()
  external double top_p;

  /// Random seed.
  @ffi.Int32()
  external int seed;

  /// Optional language hint.
  external ffi.Pointer<ffi.Char> language;

  /// Non-zero to enable inverse text normalization.
  @ffi.Int32()
  external int itn;

  /// Optional hotwords text.
  external ffi.Pointer<ffi.Char> hotwords;

  static ffi.Pointer<SherpaOnnxOfflineFunASRNanoModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> encoder_adaptor,
    required ffi.Pointer<ffi.Char> llm,
    required ffi.Pointer<ffi.Char> embedding,
    required ffi.Pointer<ffi.Char> tokenizer,
    required ffi.Pointer<ffi.Char> system_prompt,
    required ffi.Pointer<ffi.Char> user_prompt,
    required int max_new_tokens,
    required double temperature,
    required double top_p,
    required int seed,
    required ffi.Pointer<ffi.Char> language,
    required int itn,
    required ffi.Pointer<ffi.Char> hotwords,
  }) => $allocator<SherpaOnnxOfflineFunASRNanoModelConfig>()
    ..ref.encoder_adaptor = encoder_adaptor
    ..ref.llm = llm
    ..ref.embedding = embedding
    ..ref.tokenizer = tokenizer
    ..ref.system_prompt = system_prompt
    ..ref.user_prompt = user_prompt
    ..ref.max_new_tokens = max_new_tokens
    ..ref.temperature = temperature
    ..ref.top_p = top_p
    ..ref.seed = seed
    ..ref.language = language
    ..ref.itn = itn
    ..ref.hotwords = hotwords;
}

/// @brief Configuration for an offline language model.
final class SherpaOnnxOfflineLMConfig extends ffi.Struct {
  /// Path to the language model.
  external ffi.Pointer<ffi.Char> model;

  /// Interpolation scale for the language model.
  @ffi.Float()
  external double scale;

  static ffi.Pointer<SherpaOnnxOfflineLMConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> model,
    required double scale,
  }) => $allocator<SherpaOnnxOfflineLMConfig>()
    ..ref.model = model
    ..ref.scale = scale;
}

/// @brief Configuration for a MedASR CTC model.
final class SherpaOnnxOfflineMedAsrCtcModelConfig extends ffi.Struct {
  /// Path to the ONNX model.
  external ffi.Pointer<ffi.Char> model;

  static ffi.Pointer<SherpaOnnxOfflineMedAsrCtcModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> model,
  }) => $allocator<SherpaOnnxOfflineMedAsrCtcModelConfig>()..ref.model = model;
}

/// @brief Model configuration shared by offline ASR recognizers.
///
/// Zero-initialize this struct before use, then fill in exactly the sub-config
/// needed by the model family you want to run.
///
/// Exactly one model family should be configured for each recognizer. For
/// example, set only one of @c transducer, @c paraformer, @c nemo_ctc,
/// @c whisper, @c tdnn, @c sense_voice, @c moonshine, @c fire_red_asr,
/// @c dolphin, @c zipformer_ctc, @c canary, @c cohere_transcribe,
/// @c wenet_ctc, @c omnilingual, @c medasr, @c funasr_nano,
/// @c fire_red_asr_ctc, or @c qwen3_asr.
///
/// If multiple model families are configured at the same time, the
/// implementation will choose one of them, and which one is used is
/// implementation-defined. Do not rely on any precedence rule.
final class SherpaOnnxOfflineModelConfig extends ffi.Struct {
  /// Non-streaming transducer model files.
  external SherpaOnnxOfflineTransducerModelConfig transducer;

  /// Non-streaming Paraformer model files.
  external SherpaOnnxOfflineParaformerModelConfig paraformer;

  /// Non-streaming NeMo CTC model files.
  external SherpaOnnxOfflineNemoEncDecCtcModelConfig nemo_ctc;

  /// Whisper model files and options.
  external SherpaOnnxOfflineWhisperModelConfig whisper;

  /// TDNN model files.
  external SherpaOnnxOfflineTdnnModelConfig tdnn;

  /// Path to the tokens file.
  external ffi.Pointer<ffi.Char> tokens;

  /// Number of backend threads.
  @ffi.Int32()
  external int num_threads;

  /// Non-zero to print debug information.
  @ffi.Int32()
  external int debug;

  /// Execution provider, for example "cpu" or "cuda".
  external ffi.Pointer<ffi.Char> provider;

  /// Optional explicit model type override.
  external ffi.Pointer<ffi.Char> model_type;

  /// Modeling unit, such as "cjkchar", "bpe", or "cjkchar+bpe".
  external ffi.Pointer<ffi.Char> modeling_unit;

  /// Path to the BPE vocabulary file when BPE is used.
  external ffi.Pointer<ffi.Char> bpe_vocab;

  /// Path to the TeleSpeech CTC model.
  external ffi.Pointer<ffi.Char> telespeech_ctc;

  /// SenseVoice configuration.
  external SherpaOnnxOfflineSenseVoiceModelConfig sense_voice;

  /// Moonshine configuration.
  external SherpaOnnxOfflineMoonshineModelConfig moonshine;

  /// FireRedAsr configuration.
  external SherpaOnnxOfflineFireRedAsrModelConfig fire_red_asr;

  /// Dolphin configuration.
  external SherpaOnnxOfflineDolphinModelConfig dolphin;

  /// Zipformer CTC configuration.
  external SherpaOnnxOfflineZipformerCtcModelConfig zipformer_ctc;

  /// Canary configuration.
  external SherpaOnnxOfflineCanaryModelConfig canary;

  /// WeNet CTC configuration.
  external SherpaOnnxOfflineWenetCtcModelConfig wenet_ctc;

  /// Omnilingual CTC configuration.
  external SherpaOnnxOfflineOmnilingualAsrCtcModelConfig omnilingual;

  /// MedASR configuration.
  external SherpaOnnxOfflineMedAsrCtcModelConfig medasr;

  /// FunASR Nano configuration.
  external SherpaOnnxOfflineFunASRNanoModelConfig funasr_nano;

  /// FireRedAsr CTC configuration.
  external SherpaOnnxOfflineFireRedAsrCtcModelConfig fire_red_asr_ctc;

  /// Qwen3-ASR configuration.
  external SherpaOnnxOfflineQwen3ASRModelConfig qwen3_asr;

  /// Cohere Transcribe configuration.
  external SherpaOnnxOfflineCohereTranscribeModelConfig cohere_transcribe;
}

/// @brief Configuration for a Moonshine model.
final class SherpaOnnxOfflineMoonshineModelConfig extends ffi.Struct {
  /// Path to the preprocessor ONNX model.
  external ffi.Pointer<ffi.Char> preprocessor;

  /// Path to the encoder ONNX model.
  external ffi.Pointer<ffi.Char> encoder;

  /// Path to the uncached decoder ONNX model.
  external ffi.Pointer<ffi.Char> uncached_decoder;

  /// Path to the cached decoder ONNX model.
  external ffi.Pointer<ffi.Char> cached_decoder;

  /// Path to the merged decoder ONNX model.
  external ffi.Pointer<ffi.Char> merged_decoder;

  static ffi.Pointer<SherpaOnnxOfflineMoonshineModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> preprocessor,
    required ffi.Pointer<ffi.Char> encoder,
    required ffi.Pointer<ffi.Char> uncached_decoder,
    required ffi.Pointer<ffi.Char> cached_decoder,
    required ffi.Pointer<ffi.Char> merged_decoder,
  }) => $allocator<SherpaOnnxOfflineMoonshineModelConfig>()
    ..ref.preprocessor = preprocessor
    ..ref.encoder = encoder
    ..ref.uncached_decoder = uncached_decoder
    ..ref.cached_decoder = cached_decoder
    ..ref.merged_decoder = merged_decoder;
}

/// @brief Configuration for a non-streaming NeMo CTC model.
final class SherpaOnnxOfflineNemoEncDecCtcModelConfig extends ffi.Struct {
  /// Path to the ONNX model.
  external ffi.Pointer<ffi.Char> model;

  static ffi.Pointer<SherpaOnnxOfflineNemoEncDecCtcModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> model,
  }) =>
      $allocator<SherpaOnnxOfflineNemoEncDecCtcModelConfig>()
        ..ref.model = model;
}

/// @brief Configuration for an omnilingual offline CTC model.
final class SherpaOnnxOfflineOmnilingualAsrCtcModelConfig extends ffi.Struct {
  /// Path to the ONNX model.
  external ffi.Pointer<ffi.Char> model;

  static ffi.Pointer<SherpaOnnxOfflineOmnilingualAsrCtcModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> model,
  }) =>
      $allocator<SherpaOnnxOfflineOmnilingualAsrCtcModelConfig>()
        ..ref.model = model;
}

/// @brief Configuration for a non-streaming Paraformer model.
final class SherpaOnnxOfflineParaformerModelConfig extends ffi.Struct {
  /// Path to the ONNX model.
  external ffi.Pointer<ffi.Char> model;

  static ffi.Pointer<SherpaOnnxOfflineParaformerModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> model,
  }) => $allocator<SherpaOnnxOfflineParaformerModelConfig>()..ref.model = model;
}

final class SherpaOnnxOfflinePunctuation extends ffi.Opaque {}

/// @brief Configuration for offline punctuation.
final class SherpaOnnxOfflinePunctuationConfig extends ffi.Struct {
  /// Model configuration.
  external SherpaOnnxOfflinePunctuationModelConfig model;
}

/// @brief Offline punctuation model configuration.
///
/// Example:
///
/// @code
/// SherpaOnnxOfflinePunctuationModelConfig model;
/// memset(&model, 0, sizeof(model));
/// model.ct_transformer =
/// "./sherpa-onnx-punct-ct-transformer-zh-en-vocab272727-2024-04-12/model.onnx";
/// model.num_threads = 1;
/// model.provider = "cpu";
/// @endcode
final class SherpaOnnxOfflinePunctuationModelConfig extends ffi.Struct {
  /// Offline punctuation model file.
  external ffi.Pointer<ffi.Char> ct_transformer;

  /// Number of inference threads.
  @ffi.Int32()
  external int num_threads;

  /// Non-zero to print debug information.
  @ffi.Int32()
  external int debug;

  /// Execution provider such as `"cpu"`.
  external ffi.Pointer<ffi.Char> provider;

  static ffi.Pointer<SherpaOnnxOfflinePunctuationModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> ct_transformer,
    required int num_threads,
    required int debug,
    required ffi.Pointer<ffi.Char> provider,
  }) => $allocator<SherpaOnnxOfflinePunctuationModelConfig>()
    ..ref.ct_transformer = ct_transformer
    ..ref.num_threads = num_threads
    ..ref.debug = debug
    ..ref.provider = provider;
}

/// @brief Configuration for an offline Qwen3-ASR model.
final class SherpaOnnxOfflineQwen3ASRModelConfig extends ffi.Struct {
  /// Path to the conv-frontend ONNX model.
  external ffi.Pointer<ffi.Char> conv_frontend;

  /// Path to the encoder ONNX model.
  external ffi.Pointer<ffi.Char> encoder;

  /// Path to the decoder ONNX model (with KV cache).
  external ffi.Pointer<ffi.Char> decoder;

  /// Path to the tokenizer directory (e.g. containing `vocab.json`).
  external ffi.Pointer<ffi.Char> tokenizer;

  /// Maximum total sequence length supported by the model.
  @ffi.Int32()
  external int max_total_len;

  /// Maximum number of new tokens to generate.
  @ffi.Int32()
  external int max_new_tokens;

  /// Sampling temperature.
  @ffi.Float()
  external double temperature;

  /// Top-p (nucleus) sampling threshold.
  @ffi.Float()
  external double top_p;

  /// Random seed for reproducible sampling.
  @ffi.Int32()
  external int seed;

  /// Optional comma-separated hotwords (UTF-8, ASCII ','), e.g. @c
  /// "foo,bar,baz".
  external ffi.Pointer<ffi.Char> hotwords;

  static ffi.Pointer<SherpaOnnxOfflineQwen3ASRModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> conv_frontend,
    required ffi.Pointer<ffi.Char> encoder,
    required ffi.Pointer<ffi.Char> decoder,
    required ffi.Pointer<ffi.Char> tokenizer,
    required int max_total_len,
    required int max_new_tokens,
    required double temperature,
    required double top_p,
    required int seed,
    required ffi.Pointer<ffi.Char> hotwords,
  }) => $allocator<SherpaOnnxOfflineQwen3ASRModelConfig>()
    ..ref.conv_frontend = conv_frontend
    ..ref.encoder = encoder
    ..ref.decoder = decoder
    ..ref.tokenizer = tokenizer
    ..ref.max_total_len = max_total_len
    ..ref.max_new_tokens = max_new_tokens
    ..ref.temperature = temperature
    ..ref.top_p = top_p
    ..ref.seed = seed
    ..ref.hotwords = hotwords;
}

final class SherpaOnnxOfflineRecognizer extends ffi.Opaque {}

/// @brief Configuration for a non-streaming ASR recognizer.
///
/// Zero-initialize this struct before use.
///
/// Example using Whisper:
///
/// @code
/// SherpaOnnxOfflineRecognizerConfig config;
/// memset(&config, 0, sizeof(config));
///
/// config.feat_config.sample_rate = 16000;
/// config.feat_config.feature_dim = 80;
///
/// config.model_config.whisper.encoder =
/// "./sherpa-onnx-whisper-tiny/tiny-encoder.onnx";
/// config.model_config.whisper.decoder =
/// "./sherpa-onnx-whisper-tiny/tiny-decoder.onnx";
/// config.model_config.whisper.language = "en";
/// config.model_config.whisper.task = "transcribe";
/// config.model_config.tokens =
/// "./sherpa-onnx-whisper-tiny/tiny-tokens.txt";
/// config.model_config.provider = "cpu";
/// config.model_config.num_threads = 1;
///
/// config.decoding_method = "greedy_search";
/// @endcode
///
/// Example using SenseVoice:
///
/// @code
/// config.model_config.sense_voice.model =
/// "./sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8/model.int8.onnx";
/// config.model_config.sense_voice.language = "auto";
/// config.model_config.sense_voice.use_itn = 1;
/// config.model_config.tokens =
/// "./sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17-int8/tokens.txt";
/// @endcode
///
/// Example using Parakeet TDT:
///
/// @code
/// config.model_config.transducer.encoder =
/// "./sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8/encoder.int8.onnx";
/// config.model_config.transducer.decoder =
/// "./sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8/decoder.int8.onnx";
/// config.model_config.transducer.joiner =
/// "./sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8/joiner.int8.onnx";
/// config.model_config.tokens =
/// "./sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8/tokens.txt";
/// config.model_config.model_type = "nemo_transducer";
/// @endcode
/// @see SherpaOnnxCreateOfflineRecognizer
final class SherpaOnnxOfflineRecognizerConfig extends ffi.Struct {
  /// Feature extraction settings.
  external SherpaOnnxFeatureConfig feat_config;

  /// Offline model configuration.
  external SherpaOnnxOfflineModelConfig model_config;

  /// Optional language model configuration.
  external SherpaOnnxOfflineLMConfig lm_config;

  /// Decoding method, for example "greedy_search" or "modified_beam_search".
  external ffi.Pointer<ffi.Char> decoding_method;

  /// Number of active paths for modified beam search.
  @ffi.Int32()
  external int max_active_paths;

  /// Path to a hotwords file.
  external ffi.Pointer<ffi.Char> hotwords_file;

  /// Bonus score added to each hotword token.
  @ffi.Float()
  external double hotwords_score;

  /// Path to punctuation or text-processing rule FSTs.
  external ffi.Pointer<ffi.Char> rule_fsts;

  /// Path to FAR archives used by text-processing rules.
  external ffi.Pointer<ffi.Char> rule_fars;

  /// Optional blank penalty applied during decoding.
  @ffi.Float()
  external double blank_penalty;

  /// Optional homophone replacement configuration.
  external SherpaOnnxHomophoneReplacerConfig hr;
}

/// @brief Recognition result for a non-streaming ASR stream.
///
/// All pointers in this struct are owned by the result object returned from
/// SherpaOnnxGetOfflineStreamResult() and become invalid after
/// SherpaOnnxDestroyOfflineRecognizerResult() is called.
/// @see SherpaOnnxGetOfflineStreamResult, SherpaOnnxDestroyOfflineRecognizerResult
final class SherpaOnnxOfflineRecognizerResult extends ffi.Struct {
  /// Recognized text.
  external ffi.Pointer<ffi.Char> text;

  /// Optional token timestamps in seconds.
  ///
  /// This field may be NULL when the model does not provide token timestamps.
  /// When non-NULL, it contains @c count entries and is parallel to
  /// @c tokens_arr.
  external ffi.Pointer<ffi.Float> timestamps;

  /// Number of token entries in @c tokens_arr and related per-token arrays.
  @ffi.Int32()
  external int count;

  /// Contiguous memory block containing token strings separated by '\0'.
  ///
  /// Use @c tokens_arr for convenient indexed access.
  external ffi.Pointer<ffi.Char> tokens;

  /// Array of @c count pointers into @c tokens.
  external ffi.Pointer<ffi.Pointer<ffi.Char>> tokens_arr;

  /// JSON serialization of the result.
  external ffi.Pointer<ffi.Char> json;

  /// Optional recognized language label.
  external ffi.Pointer<ffi.Char> lang;

  /// Optional recognized emotion label.
  external ffi.Pointer<ffi.Char> emotion;

  /// Optional recognized event label.
  external ffi.Pointer<ffi.Char> event;

  /// Optional token durations in seconds, parallel to @c tokens_arr.
  external ffi.Pointer<ffi.Float> durations;

  /// Optional token log probabilities, parallel to @c tokens_arr.
  external ffi.Pointer<ffi.Float> ys_log_probs;

  /// Optional segment start times in seconds, parallel to @c segment_texts_arr.
  external ffi.Pointer<ffi.Float> segment_timestamps;

  /// Optional segment durations in seconds, parallel to @c segment_texts_arr.
  external ffi.Pointer<ffi.Float> segment_durations;

  /// Contiguous memory block containing segment texts separated by '\0'.
  external ffi.Pointer<ffi.Char> segment_texts;

  /// Array of @c segment_count pointers into @c segment_texts.
  external ffi.Pointer<ffi.Pointer<ffi.Char>> segment_texts_arr;

  /// Number of segment entries in the segment-level arrays.
  @ffi.Int32()
  external int segment_count;

  static ffi.Pointer<SherpaOnnxOfflineRecognizerResult> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> text,
    required ffi.Pointer<ffi.Float> timestamps,
    required int count,
    required ffi.Pointer<ffi.Char> tokens,
    required ffi.Pointer<ffi.Pointer<ffi.Char>> tokens_arr,
    required ffi.Pointer<ffi.Char> json,
    required ffi.Pointer<ffi.Char> lang,
    required ffi.Pointer<ffi.Char> emotion,
    required ffi.Pointer<ffi.Char> event,
    required ffi.Pointer<ffi.Float> durations,
    required ffi.Pointer<ffi.Float> ys_log_probs,
    required ffi.Pointer<ffi.Float> segment_timestamps,
    required ffi.Pointer<ffi.Float> segment_durations,
    required ffi.Pointer<ffi.Char> segment_texts,
    required ffi.Pointer<ffi.Pointer<ffi.Char>> segment_texts_arr,
    required int segment_count,
  }) => $allocator<SherpaOnnxOfflineRecognizerResult>()
    ..ref.text = text
    ..ref.timestamps = timestamps
    ..ref.count = count
    ..ref.tokens = tokens
    ..ref.tokens_arr = tokens_arr
    ..ref.json = json
    ..ref.lang = lang
    ..ref.emotion = emotion
    ..ref.event = event
    ..ref.durations = durations
    ..ref.ys_log_probs = ys_log_probs
    ..ref.segment_timestamps = segment_timestamps
    ..ref.segment_durations = segment_durations
    ..ref.segment_texts = segment_texts
    ..ref.segment_texts_arr = segment_texts_arr
    ..ref.segment_count = segment_count;
}

/// @brief Configuration for a SenseVoice model.
final class SherpaOnnxOfflineSenseVoiceModelConfig extends ffi.Struct {
  /// Path to the ONNX model.
  external ffi.Pointer<ffi.Char> model;

  /// Optional language hint.
  external ffi.Pointer<ffi.Char> language;

  /// Non-zero to enable inverse text normalization.
  @ffi.Int32()
  external int use_itn;

  static ffi.Pointer<SherpaOnnxOfflineSenseVoiceModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> model,
    required ffi.Pointer<ffi.Char> language,
    required int use_itn,
  }) => $allocator<SherpaOnnxOfflineSenseVoiceModelConfig>()
    ..ref.model = model
    ..ref.language = language
    ..ref.use_itn = use_itn;
}

final class SherpaOnnxOfflineSourceSeparation extends ffi.Opaque {}

/// @brief Top-level source-separation configuration.
final class SherpaOnnxOfflineSourceSeparationConfig extends ffi.Struct {
  external SherpaOnnxOfflineSourceSeparationModelConfig model;
}

/// @brief Source-separation model configuration.
final class SherpaOnnxOfflineSourceSeparationModelConfig extends ffi.Struct {
  external SherpaOnnxOfflineSourceSeparationSpleeterModelConfig spleeter;

  external SherpaOnnxOfflineSourceSeparationUvrModelConfig uvr;

  @ffi.Int32()
  external int num_threads;

  @ffi.Int32()
  external int debug;

  external ffi.Pointer<ffi.Char> provider;
}

/// @brief Spleeter source-separation model configuration.
final class SherpaOnnxOfflineSourceSeparationSpleeterModelConfig
    extends ffi.Struct {
  /// Path to the vocals ONNX model.
  external ffi.Pointer<ffi.Char> vocals;

  /// Path to the accompaniment ONNX model.
  external ffi.Pointer<ffi.Char> accompaniment;

  static ffi.Pointer<SherpaOnnxOfflineSourceSeparationSpleeterModelConfig>
  $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> vocals,
    required ffi.Pointer<ffi.Char> accompaniment,
  }) => $allocator<SherpaOnnxOfflineSourceSeparationSpleeterModelConfig>()
    ..ref.vocals = vocals
    ..ref.accompaniment = accompaniment;
}

/// @brief UVR (MDX-Net) source-separation model configuration.
final class SherpaOnnxOfflineSourceSeparationUvrModelConfig extends ffi.Struct {
  /// Path to the UVR ONNX model.
  external ffi.Pointer<ffi.Char> model;

  static ffi.Pointer<SherpaOnnxOfflineSourceSeparationUvrModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> model,
  }) =>
      $allocator<SherpaOnnxOfflineSourceSeparationUvrModelConfig>()
        ..ref.model = model;
}

final class SherpaOnnxOfflineSpeakerDiarization extends ffi.Opaque {}

/// @brief Configuration for offline speaker diarization.
///
/// Example based on `offline-sepaker-diarization-c-api.c`:
///
/// @code
/// SherpaOnnxOfflineSpeakerDiarizationConfig config;
/// memset(&config, 0, sizeof(config));
/// config.segmentation.pyannote.model =
/// "./sherpa-onnx-pyannote-segmentation-3-0/model.onnx";
/// config.embedding.model =
/// "./3dspeaker_speech_eres2net_base_sv_zh-cn_3dspeaker_16k.onnx";
/// config.clustering.num_clusters = 4;
/// @endcode
final class SherpaOnnxOfflineSpeakerDiarizationConfig extends ffi.Struct {
  /// Speaker segmentation model configuration.
  external SherpaOnnxOfflineSpeakerSegmentationModelConfig segmentation;

  /// Speaker embedding extractor configuration.
  external SherpaOnnxSpeakerEmbeddingExtractorConfig embedding;

  /// Clustering configuration.
  external SherpaOnnxFastClusteringConfig clustering;

  /// Segments shorter than this duration in seconds are discarded.
  @ffi.Float()
  external double min_duration_on;

  /// Small gaps shorter than this duration in seconds may be merged.
  @ffi.Float()
  external double min_duration_off;
}

final class SherpaOnnxOfflineSpeakerDiarizationResult extends ffi.Opaque {}

/// @brief One diarization segment.
final class SherpaOnnxOfflineSpeakerDiarizationSegment extends ffi.Struct {
  /// Segment start time in seconds.
  @ffi.Float()
  external double start;

  /// Segment end time in seconds.
  @ffi.Float()
  external double end;

  /// Speaker label, typically an integer cluster ID.
  @ffi.Int32()
  external int speaker;

  /// Per-segment confidence in [-1, 1] (higher is more confident), or -2 if
  /// unavailable (compute_confidence disabled, or the score could not be
  /// computed for this segment).
  @ffi.Float()
  external double confidence;

  static ffi.Pointer<SherpaOnnxOfflineSpeakerDiarizationSegment> $allocate(
    ffi.Allocator $allocator, {
    required double start,
    required double end,
    required int speaker,
    required double confidence,
  }) => $allocator<SherpaOnnxOfflineSpeakerDiarizationSegment>()
    ..ref.start = start
    ..ref.end = end
    ..ref.speaker = speaker
    ..ref.confidence = confidence;
}

/// @brief Segmentation model configuration for offline speaker diarization.
///
/// Configure exactly one model family. If multiple model families are provided,
/// one is chosen and the choice is implementation-defined.
final class SherpaOnnxOfflineSpeakerSegmentationModelConfig extends ffi.Struct {
  /// Pyannote segmentation model configuration.
  external SherpaOnnxOfflineSpeakerSegmentationPyannoteModelConfig pyannote;

  /// Number of inference threads.
  @ffi.Int32()
  external int num_threads;

  /// Non-zero to print debug information.
  @ffi.Int32()
  external int debug;

  /// Execution provider such as `"cpu"`.
  external ffi.Pointer<ffi.Char> provider;
}

/// @brief Pyannote speaker-segmentation model configuration.
final class SherpaOnnxOfflineSpeakerSegmentationPyannoteModelConfig
    extends ffi.Struct {
  /// Segmentation model filename.
  external ffi.Pointer<ffi.Char> model;

  /// Sliding-window shift as a fraction of the model window size.
  ///
  /// Must be in (0, 1]. Set to 0 (or a negative value) to use the default of
  /// 0.1.
  @ffi.Float()
  external double window_shift_ratio;

  static ffi.Pointer<SherpaOnnxOfflineSpeakerSegmentationPyannoteModelConfig>
  $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> model,
    required double window_shift_ratio,
  }) => $allocator<SherpaOnnxOfflineSpeakerSegmentationPyannoteModelConfig>()
    ..ref.model = model
    ..ref.window_shift_ratio = window_shift_ratio;
}

final class SherpaOnnxOfflineSpeechDenoiser extends ffi.Opaque {}

/// @brief Configuration for offline speech denoising.
final class SherpaOnnxOfflineSpeechDenoiserConfig extends ffi.Struct {
  /// Model configuration.
  external SherpaOnnxOfflineSpeechDenoiserModelConfig model;
}

/// @brief DPDFNet offline denoiser model configuration.
final class SherpaOnnxOfflineSpeechDenoiserDpdfNetModelConfig
    extends ffi.Struct {
  /// Model filename.
  external ffi.Pointer<ffi.Char> model;

  /// Offline attenuation limit in dB.
  ///
  /// Values greater than 0 limit suppression by blending aligned noisy spectra
  /// into the enhanced spectra with a noisy-signal weight of
  /// `10^(-limit_db / 20)`. The maximum finite value is 100. Set to 0 or
  /// infinity to disable the limit.
  @ffi.Float()
  external double attenuation_limit_db;

  static ffi.Pointer<SherpaOnnxOfflineSpeechDenoiserDpdfNetModelConfig>
  $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> model,
    required double attenuation_limit_db,
  }) => $allocator<SherpaOnnxOfflineSpeechDenoiserDpdfNetModelConfig>()
    ..ref.model = model
    ..ref.attenuation_limit_db = attenuation_limit_db;
}

/// @brief GTCRN offline denoiser model configuration.
final class SherpaOnnxOfflineSpeechDenoiserGtcrnModelConfig extends ffi.Struct {
  /// Model filename.
  external ffi.Pointer<ffi.Char> model;

  static ffi.Pointer<SherpaOnnxOfflineSpeechDenoiserGtcrnModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> model,
  }) =>
      $allocator<SherpaOnnxOfflineSpeechDenoiserGtcrnModelConfig>()
        ..ref.model = model;
}

/// @brief Speech denoiser model configuration shared by offline and online APIs.
///
/// Configure exactly one model family. If multiple model families are provided,
/// one is chosen and the choice is implementation-defined.
final class SherpaOnnxOfflineSpeechDenoiserModelConfig extends ffi.Struct {
  /// GTCRN model configuration.
  external SherpaOnnxOfflineSpeechDenoiserGtcrnModelConfig gtcrn;

  /// Number of inference threads.
  @ffi.Int32()
  external int num_threads;

  /// Non-zero to print debug information.
  @ffi.Int32()
  external int debug;

  /// Execution provider such as `"cpu"`.
  external ffi.Pointer<ffi.Char> provider;

  /// DPDFNet model configuration.
  external SherpaOnnxOfflineSpeechDenoiserDpdfNetModelConfig dpdfnet;
}

final class SherpaOnnxOfflineStream extends ffi.Opaque {}

/// @brief Configuration for a TDNN model.
final class SherpaOnnxOfflineTdnnModelConfig extends ffi.Struct {
  /// Path to the ONNX model.
  external ffi.Pointer<ffi.Char> model;

  static ffi.Pointer<SherpaOnnxOfflineTdnnModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> model,
  }) => $allocator<SherpaOnnxOfflineTdnnModelConfig>()..ref.model = model;
}

/// @brief Configuration for a non-streaming transducer model.
final class SherpaOnnxOfflineTransducerModelConfig extends ffi.Struct {
  /// Path to the encoder ONNX model.
  external ffi.Pointer<ffi.Char> encoder;

  /// Path to the decoder ONNX model.
  external ffi.Pointer<ffi.Char> decoder;

  /// Path to the joiner ONNX model.
  external ffi.Pointer<ffi.Char> joiner;

  static ffi.Pointer<SherpaOnnxOfflineTransducerModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> encoder,
    required ffi.Pointer<ffi.Char> decoder,
    required ffi.Pointer<ffi.Char> joiner,
  }) => $allocator<SherpaOnnxOfflineTransducerModelConfig>()
    ..ref.encoder = encoder
    ..ref.decoder = decoder
    ..ref.joiner = joiner;
}

final class SherpaOnnxOfflineTts extends ffi.Opaque {}

/// @brief Configuration for offline text-to-speech.
///
/// @code
/// SherpaOnnxOfflineTtsConfig config;
/// memset(&config, 0, sizeof(config));
///
/// config.model.kokoro.model = "./kokoro-en-v0_19/model.onnx";
/// config.model.kokoro.voices = "./kokoro-en-v0_19/voices.bin";
/// config.model.kokoro.tokens = "./kokoro-en-v0_19/tokens.txt";
/// config.model.kokoro.data_dir = "./kokoro-en-v0_19/espeak-ng-data";
/// config.model.num_threads = 2;
/// config.model.provider = "cpu";
/// config.model.debug = 0;
/// config.max_num_sentences = 2;
/// @endcode
/// @see SherpaOnnxCreateOfflineTts
final class SherpaOnnxOfflineTtsConfig extends ffi.Struct {
  /// TTS model configuration.
  external SherpaOnnxOfflineTtsModelConfig model;

  /// Optional comma-separated rule FST list.
  external ffi.Pointer<ffi.Char> rule_fsts;

  /// Maximum number of sentences processed per chunk.
  @ffi.Int32()
  external int max_num_sentences;

  /// Optional FAR archives used by text normalization rules.
  external ffi.Pointer<ffi.Char> rule_fars;

  /// Default silence scale between sentences.
  @ffi.Float()
  external double silence_scale;
}

/// @brief Configuration for a Kitten TTS model.
final class SherpaOnnxOfflineTtsKittenModelConfig extends ffi.Struct {
  /// Path to the Kitten model.
  external ffi.Pointer<ffi.Char> model;

  /// Path to the Kitten voices file.
  external ffi.Pointer<ffi.Char> voices;

  /// Path to the tokens file.
  external ffi.Pointer<ffi.Char> tokens;

  /// Optional path to espeak-ng-data.
  external ffi.Pointer<ffi.Char> data_dir;

  /// Speech rate scale. Values < 1 are slower; values > 1 are faster.
  @ffi.Float()
  external double length_scale;

  static ffi.Pointer<SherpaOnnxOfflineTtsKittenModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> model,
    required ffi.Pointer<ffi.Char> voices,
    required ffi.Pointer<ffi.Char> tokens,
    required ffi.Pointer<ffi.Char> data_dir,
    required double length_scale,
  }) => $allocator<SherpaOnnxOfflineTtsKittenModelConfig>()
    ..ref.model = model
    ..ref.voices = voices
    ..ref.tokens = tokens
    ..ref.data_dir = data_dir
    ..ref.length_scale = length_scale;
}

/// @brief Configuration for a Kokoro TTS model.
final class SherpaOnnxOfflineTtsKokoroModelConfig extends ffi.Struct {
  /// Path to the Kokoro model, for example `./kokoro-en-v0_19/model.onnx`.
  external ffi.Pointer<ffi.Char> model;

  /// Path to the Kokoro voices file.
  external ffi.Pointer<ffi.Char> voices;

  /// Path to the tokens file.
  external ffi.Pointer<ffi.Char> tokens;

  /// Optional path to espeak-ng-data.
  external ffi.Pointer<ffi.Char> data_dir;

  /// Speech rate scale. Values < 1 are slower; values > 1 are faster.
  @ffi.Float()
  external double length_scale;

  /// Unused legacy field kept for ABI compatibility.
  external ffi.Pointer<ffi.Char> dict_dir;

  /// Optional lexicon file.
  external ffi.Pointer<ffi.Char> lexicon;

  /// Optional language hint.
  external ffi.Pointer<ffi.Char> lang;

  static ffi.Pointer<SherpaOnnxOfflineTtsKokoroModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> model,
    required ffi.Pointer<ffi.Char> voices,
    required ffi.Pointer<ffi.Char> tokens,
    required ffi.Pointer<ffi.Char> data_dir,
    required double length_scale,
    required ffi.Pointer<ffi.Char> dict_dir,
    required ffi.Pointer<ffi.Char> lexicon,
    required ffi.Pointer<ffi.Char> lang,
  }) => $allocator<SherpaOnnxOfflineTtsKokoroModelConfig>()
    ..ref.model = model
    ..ref.voices = voices
    ..ref.tokens = tokens
    ..ref.data_dir = data_dir
    ..ref.length_scale = length_scale
    ..ref.dict_dir = dict_dir
    ..ref.lexicon = lexicon
    ..ref.lang = lang;
}

/// @brief Configuration for a Matcha TTS model.
final class SherpaOnnxOfflineTtsMatchaModelConfig extends ffi.Struct {
  /// Path to the Matcha acoustic model.
  external ffi.Pointer<ffi.Char> acoustic_model;

  /// Path to the vocoder model, for example `./vocos-22khz-univ.onnx`.
  external ffi.Pointer<ffi.Char> vocoder;

  /// Path to the lexicon file.
  external ffi.Pointer<ffi.Char> lexicon;

  /// Path to the tokens file.
  external ffi.Pointer<ffi.Char> tokens;

  /// Optional path to espeak-ng-data.
  external ffi.Pointer<ffi.Char> data_dir;

  /// Matcha noise scale.
  @ffi.Float()
  external double noise_scale;

  /// Speech rate scale. Values < 1 are slower; values > 1 are faster.
  @ffi.Float()
  external double length_scale;

  /// Unused legacy field kept for ABI compatibility.
  external ffi.Pointer<ffi.Char> dict_dir;

  static ffi.Pointer<SherpaOnnxOfflineTtsMatchaModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> acoustic_model,
    required ffi.Pointer<ffi.Char> vocoder,
    required ffi.Pointer<ffi.Char> lexicon,
    required ffi.Pointer<ffi.Char> tokens,
    required ffi.Pointer<ffi.Char> data_dir,
    required double noise_scale,
    required double length_scale,
    required ffi.Pointer<ffi.Char> dict_dir,
  }) => $allocator<SherpaOnnxOfflineTtsMatchaModelConfig>()
    ..ref.acoustic_model = acoustic_model
    ..ref.vocoder = vocoder
    ..ref.lexicon = lexicon
    ..ref.tokens = tokens
    ..ref.data_dir = data_dir
    ..ref.noise_scale = noise_scale
    ..ref.length_scale = length_scale
    ..ref.dict_dir = dict_dir;
}

/// @brief Configuration shared by offline TTS models.
///
/// Exactly one TTS model family should be configured. For example, set only one
/// of @c vits, @c matcha, @c kokoro, @c kitten, @c zipvoice, @c pocket, or
/// @c supertonic.
///
/// If multiple model families are configured at the same time, the
/// implementation will choose one of them, and which one is used is
/// implementation-defined. Do not rely on any precedence rule.
///
/// Concrete example model packages in this repository include:
/// - `kokoro-en-v0_19`
/// - `sherpa-onnx-pocket-tts-int8-2026-01-26`
/// - `matcha-icefall-en_US-ljspeech`
/// - `sherpa-onnx-zipvoice-distill-int8-zh-en-emilia`
final class SherpaOnnxOfflineTtsModelConfig extends ffi.Struct {
  /// VITS configuration.
  external SherpaOnnxOfflineTtsVitsModelConfig vits;

  /// Number of backend threads.
  @ffi.Int32()
  external int num_threads;

  /// Non-zero to print debug information.
  @ffi.Int32()
  external int debug;

  /// Execution provider, for example "cpu" or "cuda".
  external ffi.Pointer<ffi.Char> provider;

  /// Matcha configuration.
  external SherpaOnnxOfflineTtsMatchaModelConfig matcha;

  /// Kokoro configuration.
  external SherpaOnnxOfflineTtsKokoroModelConfig kokoro;

  /// Kitten configuration.
  external SherpaOnnxOfflineTtsKittenModelConfig kitten;

  /// ZipVoice configuration.
  external SherpaOnnxOfflineTtsZipvoiceModelConfig zipvoice;

  /// Pocket configuration.
  external SherpaOnnxOfflineTtsPocketModelConfig pocket;

  /// Supertonic configuration.
  external SherpaOnnxOfflineTtsSupertonicModelConfig supertonic;
}

/// @brief Configuration for a Pocket TTS model.
final class SherpaOnnxOfflineTtsPocketModelConfig extends ffi.Struct {
  /// Path to `lm_flow*.onnx`.
  external ffi.Pointer<ffi.Char> lm_flow;

  /// Path to `lm_main*.onnx`.
  external ffi.Pointer<ffi.Char> lm_main;

  /// Path to the Pocket encoder model.
  external ffi.Pointer<ffi.Char> encoder;

  /// Path to the Pocket decoder model.
  external ffi.Pointer<ffi.Char> decoder;

  /// Path to the text conditioner model.
  external ffi.Pointer<ffi.Char> text_conditioner;

  /// Path to `vocab.json`.
  external ffi.Pointer<ffi.Char> vocab_json;

  /// Path to `token_scores.json`.
  external ffi.Pointer<ffi.Char> token_scores_json;

  /// Voice embedding cache capacity.
  @ffi.Int32()
  external int voice_embedding_cache_capacity;

  static ffi.Pointer<SherpaOnnxOfflineTtsPocketModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> lm_flow,
    required ffi.Pointer<ffi.Char> lm_main,
    required ffi.Pointer<ffi.Char> encoder,
    required ffi.Pointer<ffi.Char> decoder,
    required ffi.Pointer<ffi.Char> text_conditioner,
    required ffi.Pointer<ffi.Char> vocab_json,
    required ffi.Pointer<ffi.Char> token_scores_json,
    required int voice_embedding_cache_capacity,
  }) => $allocator<SherpaOnnxOfflineTtsPocketModelConfig>()
    ..ref.lm_flow = lm_flow
    ..ref.lm_main = lm_main
    ..ref.encoder = encoder
    ..ref.decoder = decoder
    ..ref.text_conditioner = text_conditioner
    ..ref.vocab_json = vocab_json
    ..ref.token_scores_json = token_scores_json
    ..ref.voice_embedding_cache_capacity = voice_embedding_cache_capacity;
}

/// @brief Configuration for a Supertonic TTS model.
final class SherpaOnnxOfflineTtsSupertonicModelConfig extends ffi.Struct {
  /// Path to the duration predictor model.
  external ffi.Pointer<ffi.Char> duration_predictor;

  /// Path to the text encoder model.
  external ffi.Pointer<ffi.Char> text_encoder;

  /// Path to the vector estimator model.
  external ffi.Pointer<ffi.Char> vector_estimator;

  /// Path to the vocoder model.
  external ffi.Pointer<ffi.Char> vocoder;

  /// Path to `tts.json`.
  external ffi.Pointer<ffi.Char> tts_json;

  /// Path to the unicode indexer file.
  external ffi.Pointer<ffi.Char> unicode_indexer;

  /// Path to the voice style file.
  external ffi.Pointer<ffi.Char> voice_style;

  static ffi.Pointer<SherpaOnnxOfflineTtsSupertonicModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> duration_predictor,
    required ffi.Pointer<ffi.Char> text_encoder,
    required ffi.Pointer<ffi.Char> vector_estimator,
    required ffi.Pointer<ffi.Char> vocoder,
    required ffi.Pointer<ffi.Char> tts_json,
    required ffi.Pointer<ffi.Char> unicode_indexer,
    required ffi.Pointer<ffi.Char> voice_style,
  }) => $allocator<SherpaOnnxOfflineTtsSupertonicModelConfig>()
    ..ref.duration_predictor = duration_predictor
    ..ref.text_encoder = text_encoder
    ..ref.vector_estimator = vector_estimator
    ..ref.vocoder = vocoder
    ..ref.tts_json = tts_json
    ..ref.unicode_indexer = unicode_indexer
    ..ref.voice_style = voice_style;
}

/// @brief Configuration for a VITS TTS model.
final class SherpaOnnxOfflineTtsVitsModelConfig extends ffi.Struct {
  /// Path to the VITS ONNX model, for example `./vits-ljs.onnx`.
  external ffi.Pointer<ffi.Char> model;

  /// Path to the lexicon file. Ignored if @c data_dir is provided.
  external ffi.Pointer<ffi.Char> lexicon;

  /// Path to the tokens file.
  external ffi.Pointer<ffi.Char> tokens;

  /// Optional path to espeak-ng-data.
  external ffi.Pointer<ffi.Char> data_dir;

  /// VITS noise scale.
  @ffi.Float()
  external double noise_scale;

  /// VITS duration noise scale.
  @ffi.Float()
  external double noise_scale_w;

  /// Speech rate scale. Values < 1 are slower; values > 1 are faster.
  @ffi.Float()
  external double length_scale;

  /// Unused legacy field kept for ABI compatibility.
  external ffi.Pointer<ffi.Char> dict_dir;

  static ffi.Pointer<SherpaOnnxOfflineTtsVitsModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> model,
    required ffi.Pointer<ffi.Char> lexicon,
    required ffi.Pointer<ffi.Char> tokens,
    required ffi.Pointer<ffi.Char> data_dir,
    required double noise_scale,
    required double noise_scale_w,
    required double length_scale,
    required ffi.Pointer<ffi.Char> dict_dir,
  }) => $allocator<SherpaOnnxOfflineTtsVitsModelConfig>()
    ..ref.model = model
    ..ref.lexicon = lexicon
    ..ref.tokens = tokens
    ..ref.data_dir = data_dir
    ..ref.noise_scale = noise_scale
    ..ref.noise_scale_w = noise_scale_w
    ..ref.length_scale = length_scale
    ..ref.dict_dir = dict_dir;
}

/// @brief Configuration for a ZipVoice TTS model.
final class SherpaOnnxOfflineTtsZipvoiceModelConfig extends ffi.Struct {
  /// Path to the tokens file.
  external ffi.Pointer<ffi.Char> tokens;

  /// Path to the ZipVoice encoder model.
  external ffi.Pointer<ffi.Char> encoder;

  /// Path to the ZipVoice decoder model.
  external ffi.Pointer<ffi.Char> decoder;

  /// Path to the vocoder model.
  external ffi.Pointer<ffi.Char> vocoder;

  /// Optional path to espeak-ng-data.
  external ffi.Pointer<ffi.Char> data_dir;

  /// Path to the lexicon file.
  external ffi.Pointer<ffi.Char> lexicon;

  /// Feature scaling factor.
  @ffi.Float()
  external double feat_scale;

  /// Time shift parameter.
  @ffi.Float()
  external double t_shift;

  /// Target RMS parameter.
  @ffi.Float()
  external double target_rms;

  /// Guidance scale parameter.
  @ffi.Float()
  external double guidance_scale;

  static ffi.Pointer<SherpaOnnxOfflineTtsZipvoiceModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> tokens,
    required ffi.Pointer<ffi.Char> encoder,
    required ffi.Pointer<ffi.Char> decoder,
    required ffi.Pointer<ffi.Char> vocoder,
    required ffi.Pointer<ffi.Char> data_dir,
    required ffi.Pointer<ffi.Char> lexicon,
    required double feat_scale,
    required double t_shift,
    required double target_rms,
    required double guidance_scale,
  }) => $allocator<SherpaOnnxOfflineTtsZipvoiceModelConfig>()
    ..ref.tokens = tokens
    ..ref.encoder = encoder
    ..ref.decoder = decoder
    ..ref.vocoder = vocoder
    ..ref.data_dir = data_dir
    ..ref.lexicon = lexicon
    ..ref.feat_scale = feat_scale
    ..ref.t_shift = t_shift
    ..ref.target_rms = target_rms
    ..ref.guidance_scale = guidance_scale;
}

/// @brief Configuration for an offline WeNet CTC model.
final class SherpaOnnxOfflineWenetCtcModelConfig extends ffi.Struct {
  /// Path to the ONNX model.
  external ffi.Pointer<ffi.Char> model;

  static ffi.Pointer<SherpaOnnxOfflineWenetCtcModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> model,
  }) => $allocator<SherpaOnnxOfflineWenetCtcModelConfig>()..ref.model = model;
}

/// @brief Configuration for a non-streaming Whisper model.
final class SherpaOnnxOfflineWhisperModelConfig extends ffi.Struct {
  /// Path to the encoder ONNX model.
  external ffi.Pointer<ffi.Char> encoder;

  /// Path to the decoder ONNX model.
  external ffi.Pointer<ffi.Char> decoder;

  /// Optional language hint, for example "en" or "zh".
  external ffi.Pointer<ffi.Char> language;

  /// Optional Whisper task such as "transcribe" or "translate".
  external ffi.Pointer<ffi.Char> task;

  /// Number of tail padding frames appended internally.
  @ffi.Int32()
  external int tail_paddings;

  /// Non-zero to enable token-level timestamps when supported by the model.
  @ffi.Int32()
  external int enable_token_timestamps;

  /// Non-zero to enable Whisper segment-level timestamps.
  @ffi.Int32()
  external int enable_segment_timestamps;

  static ffi.Pointer<SherpaOnnxOfflineWhisperModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> encoder,
    required ffi.Pointer<ffi.Char> decoder,
    required ffi.Pointer<ffi.Char> language,
    required ffi.Pointer<ffi.Char> task,
    required int tail_paddings,
    required int enable_token_timestamps,
    required int enable_segment_timestamps,
  }) => $allocator<SherpaOnnxOfflineWhisperModelConfig>()
    ..ref.encoder = encoder
    ..ref.decoder = decoder
    ..ref.language = language
    ..ref.task = task
    ..ref.tail_paddings = tail_paddings
    ..ref.enable_token_timestamps = enable_token_timestamps
    ..ref.enable_segment_timestamps = enable_segment_timestamps;
}

/// @brief Zipformer audio-tagging model configuration.
final class SherpaOnnxOfflineZipformerAudioTaggingModelConfig
    extends ffi.Struct {
  /// Model filename.
  external ffi.Pointer<ffi.Char> model;

  static ffi.Pointer<SherpaOnnxOfflineZipformerAudioTaggingModelConfig>
  $allocate(ffi.Allocator $allocator, {required ffi.Pointer<ffi.Char> model}) =>
      $allocator<SherpaOnnxOfflineZipformerAudioTaggingModelConfig>()
        ..ref.model = model;
}

/// @brief Configuration for an offline Zipformer CTC model.
final class SherpaOnnxOfflineZipformerCtcModelConfig extends ffi.Struct {
  /// Path to the ONNX model.
  external ffi.Pointer<ffi.Char> model;

  static ffi.Pointer<SherpaOnnxOfflineZipformerCtcModelConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> model,
  }) =>
      $allocator<SherpaOnnxOfflineZipformerCtcModelConfig>()..ref.model = model;
}

/// @brief Configuration for speaker embedding extraction.
///
/// Example using
/// `3dspeaker_speech_campplus_sv_zh-cn_16k-common.onnx`:
///
/// @code
/// SherpaOnnxSpeakerEmbeddingExtractorConfig config;
/// memset(&config, 0, sizeof(config));
/// config.model = "./3dspeaker_speech_campplus_sv_zh-cn_16k-common.onnx";
/// config.num_threads = 1;
/// config.provider = "cpu";
/// @endcode
/// @see SherpaOnnxCreateSpeakerEmbeddingExtractor
final class SherpaOnnxSpeakerEmbeddingExtractorConfig extends ffi.Struct {
  /// Speaker embedding model file.
  external ffi.Pointer<ffi.Char> model;

  /// Number of inference threads.
  @ffi.Int32()
  external int num_threads;

  /// Non-zero to print debug information.
  @ffi.Int32()
  external int debug;

  /// Execution provider such as `"cpu"`.
  external ffi.Pointer<ffi.Char> provider;

  static ffi.Pointer<SherpaOnnxSpeakerEmbeddingExtractorConfig> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> model,
    required int num_threads,
    required int debug,
    required ffi.Pointer<ffi.Char> provider,
  }) => $allocator<SherpaOnnxSpeakerEmbeddingExtractorConfig>()
    ..ref.model = model
    ..ref.num_threads = num_threads
    ..ref.debug = debug
    ..ref.provider = provider;
}
